objects/Account.object
<CustomObject>
    <fields>
        <fullName>Super_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Super Region</label>
        <referenceTo>Super_Region__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Super_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Super Region</label>
        <referenceTo>Super_Region__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>ISO 3166 set of worldwide countries, and related ISO codes, used for address data consistency and integrity</description>
    <fields>
        <fullName>ISO3_Code__c</fullName>
        <description>ISO-3 code</description>
        <label>ISO3 Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>ISO-2 code</description>
        <label>ISO Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Super_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Super Region associated with this ISO 3166 Country</inlineHelpText>
        <label>Super Region</label>
        <referenceTo>Super_Region__c</referenceTo>
        <relationshipLabel>ISO 3166 Countries</relationshipLabel>
        <relationshipName>ISO_3166_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Super_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Super Region</label>
        <referenceTo>Super_Region__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/StateProvince__c.object
<CustomObject>
    <description>Set of states/provinces by country used for address data consistency and integrity</description>
    <fields>
        <fullName>Code__c</fullName>
        <inlineHelpText>Contains the State/Province code value (typically 2 or 3 characters).</inlineHelpText>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States/Provinces</relationshipLabel>
        <relationshipName>StatesProvinces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value_to_Validate__c</fullName>
        <inlineHelpText>Value to validate State/Province against (may contain abbreviation/short name or long name).</inlineHelpText>
        <label>Value to Validate</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>State/Province</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States/Provinces</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Super_Region__c.object
<CustomObject>
    <description>Contains Super Region records (i.e. APAC, EMEA, LAM, NAM)</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Detailed description/long name associated with the Super Region</description>
        <label>Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Super Region</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/GeoTests.cls
/* GeoTests - 2018-11-06
   by: Gary Triassi (gtriassi@trigon-group.com)
   
   Tests    Triggers:
            o AccountTriggerHandler
            o ContactTriggerHandler
            o LeadTriggerHandler
   
   			Classes:
            o AccountTriggerHandlerClass
            o ContactTriggerHandlerClass
            o LeadTriggerHandlerClass
            o CommonMethods
*/  
@isTest
private class GeoTests {

    static testMethod void geoTest() {
    	
        //-- insert Super Region
        Super_Region__c nam = new Super_Region__c(Name='NAM', Description__c='North America');
        insert nam;
        
        //-- insert Country      	
      	Country__c usa = new Country__c(Name='United States', ISO_Code__c='US', ISO3_Code__c='USA');
      	insert usa;
        
        //-- insert State/Province
        insert new StateProvince__c(Name='New York', Value_to_Validate__c='NY', Country__c=usa.Id, Code__c='NY');
    		
   		//geo (Country and State) maps
    	map<String, Country__c> countriesMapByName = new map<String, Country__c>();
    	map<String, Country__c> countriesMapByISO2 = new map<String, Country__c>();
    	map<String, Country__c> countriesMapByISO3 = new map<String, Country__c>();
		map<String, StateProvince__c> statesMapByCode = new map<String, StateProvince__c>();
		map<String, StateProvince__c> statesMapByName = new map<String, StateProvince__c>();
		map<String, StateProvince__c> statesMapByAlt = new map<String, StateProvince__c>();
		set<String> countries2Check = new set<String>();    	
    	
   		//load geo (Country and State) maps
    	CommonMethods.loadCountryMaps(countriesMapByName, countriesMapByISO2, countriesMapByISO3);
		CommonMethods.loadStatesMaps(statesMapByCode, statesMapByName, statesMapByAlt, countries2Check);	 
    	
    	//insert a new Account to test related trigger code
    	Account acct = new Account(Name='Trigon Corp', BillingCountry='USA', BillingState='New York', BillingStreet='819 Bay Road', BillingCity='Webster', 
    								BillingPostalCode='14580', Super_Region__c=nam.Id, AnnualRevenue=1000000, Website='www.trigon-corp.com');
    	insert acct;
    	
    	//call the geo validation method with both good and bad data
  		Boolean goodGeo = CommonMethods.geoFieldsValidation(0, acct, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);
  		Account badAcct = new Account(Name='Bad Account', BillingCountry=null, BillingState=null);
 		goodGeo = CommonMethods.geoFieldsValidation(0, badAcct, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);
 		goodGeo = CommonMethods.geoFieldsValidation(1, badAcct, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);  															
  		badAcct.BillingCountry = 'XYZZY';
 		goodGeo = CommonMethods.geoFieldsValidation(0, badAcct, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);
 		goodGeo = CommonMethods.geoFieldsValidation(1, badAcct, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);  		
  		badAcct.BillingCountry = 'USA';
  		badAcct.BillingState = 'XYZZY';
 		goodGeo = CommonMethods.geoFieldsValidation(0, badAcct, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);  															  		 															
 		goodGeo = CommonMethods.geoFieldsValidation(1, badAcct, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);
  		
  		//update the Account to test related trigger code
  		Account updAcct = new Account(
  			Id=acct.Id, 
  			ShippingCountry = 'United States',
	    	ShippingState = 'NY',
	    	ShippingStreet = '819 Bay Road',
	    	ShippingCity = 'Webster',
	    	ShippingPostalCode = '14580-8675');
    	try{update updAcct;}
    	catch(Exception e){}
    	
    	//insert a new Contact to test related trigger code
    	Contact cont = new Contact(FirstName='Pete', LastName='Moss', AccountId=acct.Id, MailingCountry='USA', MailingState='NY', MailingStreet='819 Bay Road', MailingCity='Webster', 
    								MailingPostalCode='14580');
    	insert cont;
    	       
    	//call the geo validation method with both good and bad data
  		goodGeo = CommonMethods.geoFieldsValidation(0, cont, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);
  		Contact badCont = new Contact(FirstName='Bad', LastName='Contact', MailingCountry=null, MailingState=null);
 		goodGeo = CommonMethods.geoFieldsValidation(0, badCont, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);
 		goodGeo = CommonMethods.geoFieldsValidation(1, badCont, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);  															
  		badCont.MailingCountry = 'XYZZY';
 		goodGeo = CommonMethods.geoFieldsValidation(0, badCont, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);
 		goodGeo = CommonMethods.geoFieldsValidation(1, badCont, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);  		
  		badCont.MailingCountry = 'USA';
  		badCont.MailingState = 'XYZZY';
 		goodGeo = CommonMethods.geoFieldsValidation(0, badCont, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);  															  		 															
 		goodGeo = CommonMethods.geoFieldsValidation(1, badCont, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);
  		
    	cont.MailingCountry = 'XX';
    	try{update cont;}
    	catch(Exception e){}
    	try{delete cont;}
    	catch(Exception e){}
    	try{delete acct;}
    	catch(Exception e){}
    	
    	//insert a new Lead to test related trigger code
    	Lead thisLead = new Lead(Company='Trigon Corp', FirstName='Pete', LastName='Moss', Country='USA', State='NY', Street='819 Bay Road', City='Webster', PostalCode='14580');
    	insert thisLead;
    	       
    	//call the geo validation method with both good and bad data
  		goodGeo = CommonMethods.geoFieldsValidation(0, thisLead, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);
  		Lead badLead = new Lead(FirstName='Bad', LastName='Lead', Country=null, State=null);
 		goodGeo = CommonMethods.geoFieldsValidation(0, badLead, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);
 		goodGeo = CommonMethods.geoFieldsValidation(1, badLead, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);  															
  		badLead.Country = 'XYZZY';
 		goodGeo = CommonMethods.geoFieldsValidation(0, badLead, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);
 		goodGeo = CommonMethods.geoFieldsValidation(1, badLead, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);  		
  		badLead.Country = 'USA';
  		badLead.State = 'XYZZY';
 		goodGeo = CommonMethods.geoFieldsValidation(0, badLead, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);  															  		 															
 		goodGeo = CommonMethods.geoFieldsValidation(1, badLead, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
  															statesMapByName, statesMapByAlt, countries2Check, false);
  		
    	thisLead.Country = 'XX';
    	try{update thisLead;}
    	catch(Exception e){}
    	try{delete thisLead;}
    	catch(Exception e){}
  															
    }//end geoTest()
    
}//end GeoTests()