objects/Account.object
<CustomObject>
    <fields>
        <fullName>Road_Tunes_months__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This field is a simplification of the IMX contract data and is required for release reporting. It shouldn't be used for any other purpose</inlineHelpText>
        <label>Road Tunes (months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sim_tunes_months__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This field is a simplification of the IMX contract data and is required for release reporting. It shouldn't be used for any other purpose</inlineHelpText>
        <label>Sim Tunes (months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
                <value>
                    <fullName>Closed Office / Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/IMX_Contract__c.object
<CustomObject>
    <description>CUSTOM OBJECT FORMERLY LABELLED "IMX CONTRACT"; NOT THE SAME AS THE NATIVE CONTRACT OBJECT</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Customer</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>IMX_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Annual_Increase_Conditions__c</fullName>
        <inlineHelpText>Contract conditions for increasing annual fees. To be read in conjunction with Fixed Fees and Inflation Country fields</inlineHelpText>
        <label>Annual Increase Conditions</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual review</fullName>
                </value>
                <value>
                    <fullName>Annual review, 14 days' notice</fullName>
                </value>
                <value>
                    <fullName>Annual review, 60 days' notice, limit 5%</fullName>
                </value>
                <value>
                    <fullName>Annual review, limit CPI</fullName>
                </value>
                <value>
                    <fullName>Annual review, limit greater of CPI or 5%</fullName>
                </value>
                <value>
                    <fullName>Annual review, one month's notice</fullName>
                </value>
                <value>
                    <fullName>Automatic increase, lesser of 3% or CPI</fullName>
                </value>
                <value>
                    <fullName>Automatic increase, lesser of 5% or CPI</fullName>
                </value>
                <value>
                    <fullName>Automatic increase, limit 3% pa</fullName>
                </value>
                <value>
                    <fullName>Automatic increase, limit CPI</fullName>
                </value>
                <value>
                    <fullName>Automatic increase, limit CPI or 90 days' notice</fullName>
                </value>
                <value>
                    <fullName>No provision for increases</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_Renew__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether the contract will automatically renew each year without any action by either party</inlineHelpText>
        <label>Auto Renew</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancel_Date__c</fullName>
        <inlineHelpText>This is the last date of support, not the date we receive notification of cancellation e.g. if the customer notifies us in March that they don't want to renew, but they are already paid up until June, then the cancellation date will be 30 June</inlineHelpText>
        <label>Cancel Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Problems__c</fullName>
        <description>Unfortunately in practice we can only use 235 characters in this field, because the contract checks report prefixes the field with "Contract problems: ". Users will still be able to enter longer text, but the report will error</description>
        <inlineHelpText>This field should only be used when the contract has been signed but there are problems that need to be resolved e.g. missing pages or appendices, or if the agreement is for a fixed period and we need to remember to renew it</inlineHelpText>
        <label>Contract Problems</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <inlineHelpText>Date contract was signed</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>DKK</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>NZD</fullName>
                </value>
                <value>
                    <fullName>QAR</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hourly_Increase_Conditions__c</fullName>
        <inlineHelpText>Contract conditions for increasing hourly rates</inlineHelpText>
        <label>Hourly Increase Conditions</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual review</fullName>
                </value>
                <value>
                    <fullName>Annual review, limit CPI</fullName>
                </value>
                <value>
                    <fullName>Annual review, one month's notice</fullName>
                </value>
                <value>
                    <fullName>Annual review, three months' notice</fullName>
                </value>
                <value>
                    <fullName>Annual review, written notice</fullName>
                </value>
                <value>
                    <fullName>Automatic increase, lesser of 5% or CPI</fullName>
                </value>
                <value>
                    <fullName>No hourly rate mentioned</fullName>
                </value>
                <value>
                    <fullName>No provision for increases</fullName>
                </value>
                <value>
                    <fullName>Prevailing rates apply</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inflation_Country__c</fullName>
        <description>Any changes to this list need to be replicated on the Inflation object</description>
        <inlineHelpText>The country to be used for inflation calculations. This must be set to NZ unless otherwise specified in the contract</inlineHelpText>
        <label>Inflation Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NZ</fullName>
                    <default>true</default>
                    <label>NZ</label>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>DK</fullName>
                </value>
                <value>
                    <fullName>EU</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoices__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Number of invoices per year</inlineHelpText>
        <label># Invoices</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Latest_Annual_Fee_History_Amount__c</fullName>
        <description>This field can't be set to read-only, because the workflow rules and code that update it won't be able to run</description>
        <label>Latest Annual Fee History Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Latest_Annual_Fee_History_Date__c</fullName>
        <description>This field can't be set to read-only because the workflow rules and code that update it won't be able to run</description>
        <label>Latest Annual Fee History Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Latest_Hourly_Fee_History_Amount__c</fullName>
        <description>This field can't be set to read-only, because the workflow rules and code that update it won't be able to run</description>
        <label>Latest Hourly Fee History Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Latest_Hourly_Fee_History_Date__c</fullName>
        <description>This field can't be set to read-only because the workflow rules and code that update it won't be able to run</description>
        <label>Latest Hourly Fee History Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Invoice_Date__c</fullName>
        <description>This field can't be set to read-only because the Apex code that updates it won't be able to run</description>
        <label>Next Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO_Status__c</fullName>
        <inlineHelpText>Whether a purchase order is required on invoices under this contract. If unsure, use To be confirmed</inlineHelpText>
        <label>PO Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To be confirmed</fullName>
                    <default>true</default>
                    <label>To be confirmed</label>
                </value>
                <value>
                    <fullName>Required</fullName>
                </value>
                <value>
                    <fullName>Not required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Embedded resource</fullName>
                </value>
                <value>
                    <fullName>Live</fullName>
                </value>
                <value>
                    <fullName>Predict</fullName>
                </value>
                <value>
                    <fullName>Theatre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <inlineHelpText>Geographic region covered by contract. This should only be populated if the account has multiple contracts for different regions</inlineHelpText>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retune_Conditions__c</fullName>
        <inlineHelpText>Whether additional work is chargeable, s&amp;m processes conditions apply etc. Also any dependence on embedded resource agreements</inlineHelpText>
        <label>Retune Conditions</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Road_Tunes_months__c</fullName>
        <inlineHelpText>Frequency of included road network retunes in months</inlineHelpText>
        <label>Road Tunes (months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sim_Tunes_months__c</fullName>
        <inlineHelpText>Frequency of included simulation retunes in months</inlineHelpText>
        <label>Sim Tunes (months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementing</fullName>
                    <default>true</default>
                    <label>Implementing</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Current Contract</fullName>
                </value>
                <value>
                    <fullName>Contract Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated by Client</fullName>
                </value>
                <value>
                    <fullName>Terminated by IMX</fullName>
                    <label>Terminated by R1/IMX</label>
                </value>
                <value>
                    <fullName>To be Deleted</fullName>
                </value>
                <value>
                    <fullName>Unknown Status</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Start_Date__c</fullName>
        <inlineHelpText>Delivery date of final release, or go live date (which one is used depends on the terms of the contract, but it's usually the delivery date). First day of work for embedded resource agreements</inlineHelpText>
        <label>Support Start Date</label>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <recordTypes>
        <fullName>Optima_Contract</fullName>
        <active>true</active>
        <label>Optima Contract</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OptimaContractTestData.cls
/**
 * @description Builder class for dealing with IMX_Contract__c records.
 * Solely used for testing, NOT a data factory.
 **/
@isTest
public with sharing class OptimaContractTestData extends SObjectTestData {

	//Get the record type ID we will be using        
    RecordType rtContract = [SELECT Id FROM RecordType WHERE SObjectType = 'IMX_Contract__c' AND DeveloperName = 'Optima_Contract'];

    /**
     * @description Overridden method to set up the default
     * Contract state for OptimaContractTestData.
     * @return A map of contract default fields.
     */
    protected override Map<Schema.SObjectField, Object> getDefaultValueMap() {
        return new Map<Schema.SObjectField, Object>{
            IMX_Contract__c.Product__c => 'Predict',
            IMX_Contract__c.Status__c => 'Active',
            IMX_Contract__c.Currency__c => 'USD',
            IMX_Contract__c.Invoices__c => 1,
            IMX_Contract__c.Support_Start_Date__c => date.parse('01/01/2013'),
            IMX_Contract__c.Contract_Start_Date__c => date.parse('01/01/2013'),
            IMX_Contract__c.Latest_Annual_Fee_History_Amount__c => 100000,
            IMX_Contract__c.Latest_Hourly_Fee_History_Amount__c => 100,
            IMX_Contract__c.Latest_Annual_Fee_History_Date__c => date.parse('01/01/2013'),
            IMX_Contract__c.Latest_Hourly_Fee_History_Date__c => date.parse('01/01/2013'),
            IMX_Contract__c.Next_Invoice_Date__c => date.parse('01/01/2014'),
            IMX_Contract__c.Annual_Increase_Conditions__c => 'none',
            IMX_Contract__c.Hourly_Increase_Conditions__c => 'lots',
            IMX_Contract__c.PO_Status__c => 'Not required',
            IMX_Contract__c.Auto_Renew__c => True,
            IMX_Contract__c.RecordTypeId => rtContract.Id
        };
    }

    /**
     * @description Returns the SObject type for OptimaContractTestData builder.
     * @return IMX_Contract__c.SObjectType.
     */
    protected override Schema.SObjectType getSObjectType() {
        return IMX_Contract__c.SObjectType;
    }

    /* Create a "with" method for each property that can be set */

    /**
     * @description Sets the account on the contract.
     * @param accountID The accountId that the contract will have.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withAccountId(Id accountId) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Account__c, accountId);
    }
    
    /**
     * @description Sets the product on the contract.
     * @param product The product that the contract will have.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withProduct(String product) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Product__c, product);
    }

    /**
     * @description Sets the status on the contract.
     * @param status The status that the contract will have.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withStatus(String status) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Status__c, status);
    }

    /**
     * @description Sets the region on the contract.
     * @param region The region that the contract will have.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withRegion(String region) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Region__c, region);
    }

    /**
     * @description Sets the inflation country on the contract.
     * @param inflationCountry The code of the country that should be used for inflation for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withInflationCountry(String inflationCountry) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Inflation_Country__c, inflationCountry);
    }

    /**
     * @description Sets the contract start date on the contract.
     * @param contractDate The date the contract was signed.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withContractDate(Date contractDate) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Contract_Start_Date__c, contractDate);
    }

    /**
     * @description Sets the support start date on the contract.
     * @param supportDate The date support started for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withSupportDate(Date supportDate) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Support_Start_Date__c, supportDate);
    }

    /**
     * @description Sets the cancellation date on the contract.
     * @param cancelDate The date the contract was cancelled.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withCancelDate(Date cancelDate) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Cancel_Date__c, cancelDate);
    }

    /**
     * @description Sets the latest annual fee history date on the contract.
     * @param annualDate The date of the latest annual increase for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withLatestAnnualDate(Date latestAnnualDate) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Latest_Annual_Fee_History_Date__c, latestAnnualDate);
    }
    
    /**
     * @description Sets the latest annual fee history amount on the contract.
     * @param annualAmount The amount of the latest annual fee for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withLatestAnnualAmount(Integer latestAnnualAmount) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Latest_Annual_Fee_History_Amount__c, latestAnnualAmount);
    }
    
    /**
     * @description Sets the latest hourly fee history date on the contract.
     * @param hourlyDate The date of the latest hourly increase for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withLatestHourlyDate(Date latestHourlyDate) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Latest_Hourly_Fee_History_Date__c, latestHourlyDate);
    }

    /**
     * @description Sets the latest hourly fee history amount on the contract.
     * @param hourlyAmount The amount of the latest hourly fee for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withLatestHourlyAmount(Integer latestHourlyAmount) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Latest_Hourly_Fee_History_Amount__c, latestHourlyAmount);
    }
    
    /**
     * @description Sets the next invoice date on the contract.
     * @param invoiceDate The date of the next invoice for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withNextInvoiceDate(Date nextInvoiceDate) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Next_Invoice_Date__c, nextInvoiceDate);
    }

    /**
     * @description Sets the road tune frequency on the contract.
     * @param roadTunes The frequency of road tunes for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withRoadTunes(Integer roadTunes) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Road_Tunes_months__c, roadTunes);
    }

    /**
     * @description Sets the sim tune frequency on the contract.
     * @param simTunes The frequency of sim tunes for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withSimTunes(Integer simTunes) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Sim_Tunes_months__c, simTunes);
    }

    /**
     * @description Sets the retune conditions on the contract.
     * @param retuneConditions The conditions that apply to retunes for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withRetuneConditions(String retuneConditions) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Retune_Conditions__c, retuneConditions);
    }

    /**
     * @description Sets the annual increase conditions on the contract.
     * @param annualConditions The conditions that apply to annual fee increases for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withAnnualConditions(String annualConditions) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Annual_Increase_Conditions__c, annualConditions);
    }

    /**
     * @description Sets the hourly increase conditions on the contract.
     * @param hourlyConditions The conditions that apply to hourly fee increases for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withHourlyConditions(String hourlyConditions) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Hourly_Increase_Conditions__c, hourlyConditions);
    }

    /**
     * @description Sets the contract problems.
     * @param problems The problems that need to be resolved for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withContractProblems(String problems) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Contract_Problems__c, problems);
    }

    /**
     * @description Sets the purchase order status.
     * @param status The status of the purchase order for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withPOStatus(String status) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.PO_Status__c, status);
    }
            
    /**
     * @description Sets the purchase order expiry.
     * @param expiry The expiry date of the purchase order for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withPOExpiry(Date expiry) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.PO_Expiry__c, expiry);
    }
            
    /**
     * @description Sets the purchase order process.
     * @param process The process for getting a purchase order for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withPOProcess(String process) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.PO_Process__c, process);
    }
            
    /**
     * @description Sets the aauto renew flag for the contract.
     * @param auto The auto-renewal flag for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withAutoRenew(Boolean auto) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Auto_Renew__c, auto);
    }
            
    /**
     * @description Sets the contract renewal date.
     * @param renewal The renewal date for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withRenewalDate(Date renewal) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Renewal_Date__c, renewal);
    }
            
    /**
     * @description Sets the contract expiry date.
     * @param expiry The expiry date for this contract.
     * @return The instance of OptimaContractTestData.
     */
    public OptimaContractTestData withExpiryDate(Date expiry) {
        return (OptimaContractTestData) withDynamicData(IMX_Contract__c.Expiry_Date__c, expiry);
    }
                
    /**
     * @description Builds the IMX_Contract__c object.
     * @return The created IMX_Contract__c object.
     */
    public IMX_Contract__c create() {
        return (IMX_Contract__c)super.buildWithReset();
    }

    /**
     * @description Inserts the built IMX_Contract__c object.
     * @return The inserted IMX_Contract__c object.
     */
    public IMX_Contract__c insertContract() {
        return (IMX_Contract__c)super.insertRecord();
    }
    
    /**
     * @description Inserts a contract using only the default values.
     * @return The inserted contract.
     */
    public IMX_Contract__c insertDefaultContract() {
        return (IMX_Contract__c) insertDefaultRecord();
    }
    
    /**
     * @description Insert the specified number of contracts.
     * @param numberOfContractsToInsert The number of contracts to insert.
     * @return The contracts that were inserted.
     */
    public List<IMX_Contract__c> insertContracts(Integer numberOfContractsToInsert) {
        return (List<IMX_Contract__c>) insertRecords(numberOfContractsToInsert);
    }
    
    /**
     * @description Gets an instance of OptimaContractTestData.
     * @return OptimaContractTestData instance.
     */
    private static OptimaContractTestData instancePriv = null;
    public static OptimaContractTestData Instance {
        get {
            if (instancePriv == null) {
                instancePriv = new OptimaContractTestData();
            }
            return instancePriv;
        }
    }

    /**
     * @description Private constructor for singleton.
     */
    private OptimaContractTestData() {
        super();
    }
}