objects/Account.object
<CustomObject>
    <fields>
        <fullName>Asset_List__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asset List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CountSolPort__c</fullName>
        <label>CountSolPort</label>
        <summaryForeignKey>SolPort__c.Account__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Competitor__c.object
<CustomObject>
    <label>Competitor</label>
    <nameField>
        <label>CompetitorName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>ISO 3166 set of worldwide countries, and related ISO codes, used for address data consistency and integrity</description>
    <fields>
        <fullName>ISO3_Code__c</fullName>
        <description>ISO-3 code</description>
        <label>ISO3 Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>ISO-2 code</description>
        <label>ISO Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SolPort__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solution Portfolio</relationshipLabel>
        <relationshipName>SolPort</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Competitor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Former__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Former</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_By__c</fullName>
        <label>Group By</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Not_a_Fit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Not a Fit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Target</label>
        <type>Checkbox</type>
    </fields>
    <label>Solution Portfolio</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>Solution Portfolio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution Portfolio</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Solution_Master__c.object
<CustomObject>
    <fields>
        <fullName>Group_By__c</fullName>
        <label>Group By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GroupBy</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <label>Solution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Solutions</valueSetName>
        </valueSet>
    </fields>
    <label>Solution Master</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Solution Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solutions Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/GroupBy.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HB</fullName>
    </customValue>
    <customValue>
        <fullName>OB</fullName>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
    </customValue>
    <customValue>
        <fullName>EMS</fullName>
    </customValue>
    <customValue>
        <fullName>MOD</fullName>
    </customValue>
    <customValue>
        <fullName>E2E</fullName>
    </customValue>
    <customValue>
        <fullName>OPT</fullName>
    </customValue>
    <masterLabel>GroupBy</masterLabel>
</GlobalValueSet>

globalValueSets/Solutions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ambulance Supplemental Payment Program ASPP</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Business Office Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Documentation Improvement Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Coding Management Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Revenue Cycle Management Full Operating Partnership</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Revenue Cycle Mgmt Co-Managed Partnership</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Consulting Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Live</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Managed Analytics Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Predict</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Experience Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Physician Advisory Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Cycle Management Services- EMS</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Cycle Management Services OB</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Integrity Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>TripTix</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Experience Technology</fullName>
    </customValue>
    <customValue>
        <fullName>DatStat</fullName>
    </customValue>
    <masterLabel>Solutions</masterLabel>
</GlobalValueSet>

classes/SolPortUpdateController_TEST.cls
@istest
public class SolPortUpdateController_TEST {
static testmethod void myTestData(){
    
     Country__c usa = new Country__c(Name='United States', ISO_Code__c='US', ISO3_Code__c='USA');
    insert usa;
      
    Account a = new Account(Name = 'Penrod Health Care');
    a.BillingCountry = usa.ISO_Code__c;
    a.Asset_List__c = true;
    Insert a; 
    
    Account b = new Account(Name = 'Test Health Care');
    b.BillingCountry = usa.ISO_Code__c;
    b.Asset_List__c = true;
    Insert b; 
    
    SolPort__c solport_Obj = new SolPort__c(Account__c = a.id, Opportunity__c = false, Not_a_Fit__c = false, Competitor__c = false, Target__c = false, Current__c = false, Former__c = false);
    Insert solport_Obj; 
    
    Solution_Master__c solmast_Obj = new Solution_Master__c( Group_By__c = 'OPT', Solution__c ='TripTix');
    Insert solmast_Obj;
    Solution_Master__c solmast_Obj2 = new Solution_Master__c( Group_By__c = 'OPT', Solution__c ='Optima Live');
    Insert solmast_Obj2;
    
    test.startTest();



    pagereference pageref = page.LaunchSPPopulate;
   
      
    Test.setCurrentPage(pageref);
    SolPortUpdateController ext = new SolPortUpdateController();
    
    
    ext.runQuery();

    
    //system.assertequals(ext.debugsoql,'select name, asset_List__c, countsolport__c  from account where asset_List__c = true');
    system.assertnotequals(ext.debugsoql.length(),0 );
    
    

        
    ext.SolPortUpdate2();
    
    
    

    
    ext.runQuery();
    
    //delete a;
    //delete b;
    
    
   
	//ext.debugsoql='123' ;
    //ext.runQuery();
    
    
    
    //try to trigger catch exception

   
  
  
    
  
  
    

        
    
    
    
   
    
    
    
    

}
}