objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
                <value>
                    <fullName>Closed Office / Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Note__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Optima_Note_Account_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Optima_Note__c</fullName>
        <label>Optima Note</label>
        <referenceTo>Optima_Note__c</referenceTo>
        <relationshipName>Optima_Note_Account_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Account Note</label>
    <nameField>
        <displayFormat>ONA-{0}</displayFormat>
        <label>Note Account Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IMX_Contract__c.object
<CustomObject>
    <description>CUSTOM OBJECT FORMERLY LABELLED "IMX CONTRACT"; NOT THE SAME AS THE NATIVE CONTRACT OBJECT</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Customer</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>IMX_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Embedded resource</fullName>
                </value>
                <value>
                    <fullName>Live</fullName>
                </value>
                <value>
                    <fullName>Predict</fullName>
                </value>
                <value>
                    <fullName>Theatre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementing</fullName>
                    <default>true</default>
                    <label>Implementing</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Current Contract</fullName>
                </value>
                <value>
                    <fullName>Contract Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated by Client</fullName>
                </value>
                <value>
                    <fullName>Terminated by IMX</fullName>
                    <label>Terminated by R1/IMX</label>
                </value>
                <value>
                    <fullName>To be Deleted</fullName>
                </value>
                <value>
                    <fullName>Unknown Status</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Optima_Note__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Live</fullName>
                </value>
                <value>
                    <fullName>NET</fullName>
                </value>
                <value>
                    <fullName>Predict</fullName>
                </value>
                <value>
                    <fullName>Theatre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stop_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, prevents additional Apex Code from running on this record.</description>
        <inlineHelpText>When checked, prevents additional Apex Code from running on this record.</inlineHelpText>
        <label>Stop Code</label>
        <type>Checkbox</type>
    </fields>
    <label>Optima Note</label>
    <nameField>
        <displayFormat>OPT-{0000}</displayFormat>
        <label>Note Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Optima Notes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OptimaNoteAccountRelationship.cls
/*********************************************************************************************
 * Name:
 * Optima Note - Account Relationship Class
 * 
 * Author:
 * Jeff Arwady | Senior Consultant
 * akaCRM
 * 
 * Description:
 * This class is activated via an On-Click JavaScipt Custom Button located on the 
 * Optima Note Object. It finds all the Account Records that have the same
 * product as the Optima Note as Identified by the IMX Contract Object that is
 * related to the Account Object.  Cancelled contracts are excluded.
 * The use of a Stop Code checkbox prevents repeated use.
 * *******************************************************************************************/

global class OptimaNoteAccountRelationship {

    @AuraEnabled
    webservice static void accountRelationship(Id optimaNoteId) {
    	
        //Declare Variables
        Optima_Note__c optimaNote = [SELECT Id, Product__c, Stop_Code__c FROM Optima_Note__c WHERE Id = :optimaNoteId];
        List<IMX_Contract__c> contracts = new List<IMX_Contract__c>();
        String accountId = NULL;
        List<Account_Note__c> notes = new List<Account_Note__c>();
        String optimaNoteProduct = optimaNote.Product__c;
        
        //Prevent repeated use of this logic on the same record
        if(optimaNote.Stop_Code__c == FALSE) {
        
            //Query the database for IMX Contracts that share their product with the originating Optima Note and are not Cancelled
            contracts = [SELECT Id, Account__c, Account__r.Name FROM IMX_Contract__c 
                         WHERE Product__c = :optimaNoteProduct AND Status__c != 'Cancelled' 
                         ORDER BY Account__r.Name];
        
            //Create an Account Note for each IMX Contract queried
            for(IMX_Contract__c imx :contracts) {
 
                if(imx.Account__c != accountId) {
            
                    Account_Note__c an = new Account_Note__c();
            
                    an.Account__c = imx.Account__c;
                    an.Optima_Note__c = optimaNoteId;
                
                    accountId = imx.Account__c;
            
                    notes.add(an);
                }
            }
            
            optimaNote.Stop_Code__c = TRUE;
            update optimaNote;   
        }
        
        //Commit the New Tables to the Database
        if(notes.size() > 0) { 
            insert notes;
        }
    }
}