objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
                <value>
                    <fullName>Closed Office / Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Competitor</fullName>
        <active>true</active>
        <label>Competitor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Competitive_Info__c.object
<CustomObject>
    <fields>
        <fullName>Competitor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor</label>
        <referenceTo>Competitor__c</referenceTo>
        <relationshipLabel>Competitive Info</relationshipLabel>
        <relationshipName>Competitive_Info</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Thru_Date__c</fullName>
        <label>Contract Thru Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <label>Related To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitive Info</relationshipLabel>
        <relationshipName>Competitive_Info</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Solution_Covered__c</fullName>
        <label>Solution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Solutions</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strengths__c</fullName>
        <label>Strengths</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Weaknesses__c</fullName>
        <label>Weaknesses</label>
        <type>TextArea</type>
    </fields>
    <label>Competitive Info</label>
    <nameField>
        <displayFormat>CI-{000000}</displayFormat>
        <label>Competitive Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SolPort__c.object
<CustomObject>
    <label>Solution Portfolio</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>Solution Portfolio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution Portfolio</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Solutions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ambulance Supplemental Payment Program ASPP</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Business Office Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Documentation Improvement Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Coding Management Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Revenue Cycle Management Full Operating Partnership</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Revenue Cycle Mgmt Co-Managed Partnership</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Consulting Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Live</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Managed Analytics Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Predict</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Experience Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Physician Advisory Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Cycle Management Services- EMS</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Cycle Management Services OB</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Integrity Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>TripTix</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Experience Technology</fullName>
    </customValue>
    <customValue>
        <fullName>DatStat</fullName>
    </customValue>
    <masterLabel>Solutions</masterLabel>
</GlobalValueSet>

classes/CompetitiveInfoExtensionClass.cls
public class CompetitiveInfoExtensionClass {


//public String groupFieldName {get; set;}    
//public SolPort__c[] SPList{get;set;}
public Competitive_Info__c[] CIList{get;set;}
public string AccountID {get; set;}  
//   public string accname {get; set;}
// String SolId;


//public void setSolId(String val)
//{
//this.SolId=val;
//}
//public String getSolId()
//{
//return this.SolId;
//}

    



     
    public CompetitiveInfoExtensionClass(ApexPages.standardController std){
        CIList=new Competitive_Info__c[]{};
        
      	
        string AccountID=ApexPages.currentPage().getParameters().get('id');
        string mySolution=ApexPages.currentPage().getParameters().get('solution');	

        
        if(AccountID==NULL){
            system.debug('No Id available');
        }
        else{
            
     
            Competitive_Info__c[] CI = new Competitive_Info__c[]{};
           
            CI=[Select Id, name, Related_To__c, Competitor_Name__c, Solution_Covered__c, Status__c, Strengths__c, weaknesses__c, Contract_Thru_Date__c from Competitive_Info__c where Related_To__c =:AccountID and Solution_covered__c =:mySolution order by Status__c ];
            
            for( Competitive_Info__c c:CI){
           
                    CIList.add(c);
                }
            
            
               
            system.debug(cilist.size());
              
            }
        }
    
       // public pageReference newCompetitor(){  
		//not being used - it is the code to open up the new competitor windo
        //pageReference pageRef = new pageReference(URL.getSalesforceBaseUrl().toExternalForm() + '/a2A/e?&retURL=' + Competitive_Info__c.id);  

        //return pageRef; 

   // } 
    

    
    //public pageReference newCompetitive(){  
		//string AccountID=ApexPages.currentPage().getParameters().get('id');
        //Account acclist = new Account();
        //acclist = [Select Id, Name  from Account where id =:AccountID Limit 1];
      
     	//string accname = acclist.name;
        
        		
        //PageReference pageRef = new PageReference(URL.getSalesforceBaseUrl().toExternalForm() + '/apex/CompetInfoNew?AccountID=' + AccountId);
        
    
		//system.debug(AccountId);
        //return pageRef; 

  //  } 

 
    }