objects/Account.object
<CustomObject>
    <fields>
        <fullName>Optima_Customer_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This code is used to identify customers for Optima support purposes, so it shouldn't be filled in for any non-Optima accounts or any prospective Optima accounts or opportunities</inlineHelpText>
        <label>Optima Customer Code</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Optima_Live_Tech_Date__c</fullName>
        <inlineHelpText>Date that the latest Live technical requirements document was sent to the customer</inlineHelpText>
        <label>Optima Live Tech Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Optima_Live_Tech_Version__c</fullName>
        <inlineHelpText>Version of the latest Live technical requirements document that was sent to the customer</inlineHelpText>
        <label>Optima Live Tech Version</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Optima_Mtc_Processes_Date__c</fullName>
        <inlineHelpText>Date that the latest support and maintenance processes document was sent to the customer</inlineHelpText>
        <label>Optima Mtc Processes Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Optima_Mtc_Processes_Version__c</fullName>
        <inlineHelpText>Version number of the latest support and maintenance processes document that has been sent to the customer</inlineHelpText>
        <label>Optima Mtc Processes Version</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Optima_Predict_Tech_Date__c</fullName>
        <inlineHelpText>Date that the latest Predict technical requirements document was sent to the customer</inlineHelpText>
        <label>Optima Predict Tech Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Optima_Predict_Tech_Version__c</fullName>
        <inlineHelpText>Version number of the latest Predict technical requirements document that was sent to the customer</inlineHelpText>
        <label>Optima Predict Tech Version</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Optima_Support_Meeting__c</fullName>
        <label>Optima Support Meeting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To be organised</fullName>
                    <default>true</default>
                    <label>To be organised</label>
                </value>
                <value>
                    <fullName>Run from NZ</fullName>
                </value>
                <value>
                    <fullName>Run from UK</fullName>
                </value>
                <value>
                    <fullName>Run from US</fullName>
                </value>
                <value>
                    <fullName>Customer declined meeting</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <inlineHelpText>Standard time only, even if daylight saving time is currently in effect</inlineHelpText>
        <label>Timezone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UTC-11 (Samoa)</fullName>
                </value>
                <value>
                    <fullName>UTC-10 (Hawaii)</fullName>
                </value>
                <value>
                    <fullName>UTC-9 (Alaska)</fullName>
                </value>
                <value>
                    <fullName>UTC-8 (Pacific)</fullName>
                </value>
                <value>
                    <fullName>UTC-7 (Mountain)</fullName>
                </value>
                <value>
                    <fullName>UTC-6 (Central)</fullName>
                </value>
                <value>
                    <fullName>UTC-5 (Eastern)</fullName>
                </value>
                <value>
                    <fullName>UTC-4 (Atlantic)</fullName>
                </value>
                <value>
                    <fullName>UTC-3 (Brazil)</fullName>
                </value>
                <value>
                    <fullName>UTC-2 (South Georgia)</fullName>
                </value>
                <value>
                    <fullName>UTC-1 (Azores)</fullName>
                </value>
                <value>
                    <fullName>UTC+0 (United Kingdom)</fullName>
                </value>
                <value>
                    <fullName>UTC+1 (Central Europe)</fullName>
                </value>
                <value>
                    <fullName>UTC+2 (Eastern Europe)</fullName>
                </value>
                <value>
                    <fullName>UTC+3 (Arabia)</fullName>
                </value>
                <value>
                    <fullName>UTC+4 (Gulf)</fullName>
                </value>
                <value>
                    <fullName>UTC+5 (Pakistan)</fullName>
                </value>
                <value>
                    <fullName>UTC+6 (Bangladesh)</fullName>
                </value>
                <value>
                    <fullName>UTC+7 (Indochina)</fullName>
                </value>
                <value>
                    <fullName>UTC+8 (Australia Western)</fullName>
                </value>
                <value>
                    <fullName>UTC+9 (Japan)</fullName>
                </value>
                <value>
                    <fullName>UTC+9.5 (Australia Central)</fullName>
                </value>
                <value>
                    <fullName>UTC+10 (Australia Eastern)</fullName>
                </value>
                <value>
                    <fullName>UTC+11 (Solomon Islands)</fullName>
                </value>
                <value>
                    <fullName>UTC+12 (New Zealand)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <inlineHelpText>Intermedix Market Segment</inlineHelpText>
        <label>Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Emergency 911</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Military</fullName>
                </value>
                <value>
                    <fullName>State/Local-Emergency Management</fullName>
                </value>
                <value>
                    <fullName>State/Local-Public Health</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>IDN</fullName>
                </value>
                <value>
                    <fullName>Physicians</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AccountTestData.cls
/**
 * @description Builder class for dealing with Account records.
 * Solely used for testing, NOT a data factory.
 **/
@isTest
public class AccountTestData extends SObjectTestData {

    /**
     * @description Overridden method to set up the default
     * Account state for AccountTestData.
     * @return A map of Account default fields.
     */
    protected override Map<Schema.SObjectField, Object> getDefaultValueMap() {
        return new Map<Schema.SObjectField, Object>{
            Account.Name => 'Test Name',
            Account.Optima_Customer_Code__c => 'Test Code 1',
            Account.Site => 'Timbuctu',
            Account.Type => 'Test Type',
            Account.Vertical__c => 'Test Vertical',
            Account.Optima_Support_Meeting__c => 'Run from NZ',
            Account.Timezone__c => 'UTC+12 (New Zealand)',
            Account.Optima_Mtc_Processes_Version__c => '1.0',
            Account.Optima_Mtc_Processes_Date__c => date.parse('01/01/2013'),
            Account.Optima_Predict_Tech_Version__c => '1.0',
            Account.Optima_Predict_Tech_Date__c => date.parse('01/01/2013'),
            Account.Optima_Live_Tech_Version__c => '1.0',
            Account.Optima_Live_Tech_Date__c => date.parse('01/01/2013'),
            Account.BillingCountry => 'United States'
        };
    }

    /**
     * @description Returns the SObject type for AccountTestData builder.
     * @return Account.SObjectType.
     */
    protected override Schema.SObjectType getSObjectType() {
        return Account.SObjectType;
    }

    /**
     * @description Sets the name on the account.
     * @param name The name that the account will have.
     * @return The instance of AccountTestData.
     */
    public AccountTestData withName(String name) {
        return (AccountTestData) withDynamicData(Account.Name, name);
    }
    
    /**
     * @description Sets the billing state on the account.
     * @param billingState The billing state that the account will have.
     * @return The instance of AccountTestData.
     */
    public AccountTestData withBillingState(String billingState) {
        return (AccountTestData) withDynamicData(Account.BillingState, billingState);
    }

    /**
     * @description Sets the optima customer code on the account.
     * @param optimaCustomerCode The optima customer code that the account will have.
     * @return The instance of AccountTestData.
     */
    public AccountTestData withOptimaCustomerCode(String optimaCustomerCode) {
        return (AccountTestData) withDynamicData(Account.Optima_Customer_Code__c, optimaCustomerCode);
    }

    /**
     * @description Sets the site on the account.
     * @param site The site that the account will have.
     * @return The instance of AccountTestData.
     */
    public AccountTestData withSite(String site) {
        return (AccountTestData) withDynamicData(Account.Site, site);
    }

    /**
     * @description Sets the type on the account.
     * @param type The type that the account will have.
     * @return The instance of AccountTestData.
     */
    public AccountTestData withType(String type) {
        return (AccountTestData) withDynamicData(Account.Type, type);
    }

    /**
     * @description Sets the vertical on the account.
     * @param vertical The vertical that the account will have.
     * @return The instance of AccountTestData.
     */
    public AccountTestData withVertical(String vertical) {
        return (AccountTestData) withDynamicData(Account.Vertical__c, vertical);
    }


    /* Create a "with" method for each property that can be set */
    
    /**
     * @description Builds the Account object.
     * @return The created Account object.
     */
    public Account create() {
        return (Account)super.buildWithReset();
    }

    /**
     * @description Inserts the built Account object.
     * @return The inserted Account object.
     */
    public Account insertAccount() {
        return (Account)super.insertRecord();
    }
    
    /**
     * @description Inserts an account using only the default values.
     * @return The inserted account.
     */
    public Account insertDefaultAccount() {
        return (Account) insertDefaultRecord();
    }
    
    /**
     * @description Insert the specified number of accounts.
     * @param numberOfAccountsToInsert The number of accounts to insert.
     * @return The accounts that were inserted.
     */
    public List<Account> insertAccounts(Integer numberOfAccountsToInsert) {
        return (List<Account>) insertRecords(numberOfAccountsToInsert);
    }
    
    /**
     * @description Gets an instance of AccountTestData.
     * @return AccountTestData instance.
     */
    public static AccountTestData Instance {
        get {
            if (Instance == null) {
                Instance = new AccountTestData();
            }
            return Instance;
        }
    }

    /**
     * @description Private constructor for singleton.
     */
    private AccountTestData() {
        super();
    }
}