objects/Account.object
<CustomObject>
    <fields>
        <fullName>Vertical__c</fullName>
        <inlineHelpText>Intermedix Market Segment</inlineHelpText>
        <label>Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Emergency 911</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Military</fullName>
                </value>
                <value>
                    <fullName>State/Local-Emergency Management</fullName>
                </value>
                <value>
                    <fullName>State/Local-Public Health</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>IDN</fullName>
                </value>
                <value>
                    <fullName>Physicians</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>ISO 3166 set of worldwide countries, and related ISO codes, used for address data consistency and integrity</description>
    <fields>
        <fullName>ISO3_Code__c</fullName>
        <description>ISO-3 code</description>
        <label>ISO3 Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>ISO-2 code</description>
        <label>ISO Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <defaultValue>IF( $RecordType.DeveloperName = "Enterprise" ,60, 
 IF ($RecordType.DeveloperName = "Modular",24,
12))</defaultValue>
        <inlineHelpText>Autopopulated based on Opp record Type but Opp owner can alter as needed. Enterprise: 60 mo, Modular: 24, Chart Audits &amp; Classes 1, All Others: 12.</inlineHelpText>
        <label>Contract Terms (Mo)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <label>Solution</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Target_Market__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enterprise Revenue Cycle Mgmt Co-Managed Partnership</fullName>
                </value>
                <value>
                    <fullName>Enterprise Revenue Cycle Management Full Operating Partnership</fullName>
                </value>
                <value>
                    <fullName>Revenue Cycle Management Services OB</fullName>
                </value>
                <value>
                    <fullName>Practice Management Services</fullName>
                </value>
                <value>
                    <fullName>Optima Live</fullName>
                </value>
                <value>
                    <fullName>Optima Predict</fullName>
                </value>
                <value>
                    <fullName>TripTix</fullName>
                </value>
                <value>
                    <fullName>Revenue Integrity Solutions</fullName>
                </value>
                <value>
                    <fullName>Physician Advisory Solutions</fullName>
                </value>
                <value>
                    <fullName>Coding Management Solutions</fullName>
                </value>
                <value>
                    <fullName>Business Office Solutions</fullName>
                </value>
                <value>
                    <fullName>Anesthesia - Revenue Cycle Management Services</fullName>
                </value>
                <value>
                    <fullName>Anesthesia - Practice Management Services</fullName>
                </value>
                <value>
                    <fullName>Anesthesia - Coding Services</fullName>
                </value>
                <value>
                    <fullName>Hospital Medicine - Revenue Cycle Management Services</fullName>
                </value>
                <value>
                    <fullName>Hospital Medicine - Practice Management Services</fullName>
                </value>
                <value>
                    <fullName>Hospital Medicine - Coding Services</fullName>
                </value>
                <value>
                    <fullName>Emergency Medicine - Revenue Cycle Management Services</fullName>
                </value>
                <value>
                    <fullName>Emergency Medicine - Practice Management Services</fullName>
                </value>
                <value>
                    <fullName>Emergency Medicine - Coding Services</fullName>
                </value>
                <value>
                    <fullName>Revenue Cycle Management Services- EMS</fullName>
                </value>
                <value>
                    <fullName>Ambulance Supplemental Payment Program ASPP</fullName>
                </value>
                <value>
                    <fullName>Optima Managed Analytics Solutions</fullName>
                </value>
                <value>
                    <fullName>Optima Consulting Solutions</fullName>
                </value>
                <value>
                    <fullName>Clinical Documentation Improvement Solutions</fullName>
                </value>
                <value>
                    <fullName>Patient Experience Solutions</fullName>
                </value>
                <value>
                    <fullName>Patient Experience Technology</fullName>
                </value>
                <value>
                    <fullName>DatStat</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                    <isActive>false</isActive>
                    <label>Hybrid</label>
                </value>
                <value>
                    <fullName>Modular - Business Office Solutions</fullName>
                    <isActive>false</isActive>
                    <label>Modular - Business Office Solutions</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Anticipated start date when the customer will begin using R1 services or products.  This is important for revenue forecasting.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target_Market__c</fullName>
        <label>Target Market</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Vertical__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Hospitals and Health Systems</fullName>
                </value>
                <value>
                    <fullName>Office-Based Physicians</fullName>
                </value>
                <value>
                    <fullName>Hospital-Based Physicians</fullName>
                </value>
                <value>
                    <fullName>FD, Municipalities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <inlineHelpText>If left blank, will be set to the Account Vertical after saving. This is used in quote approval processes, so make sure it is accurate.</inlineHelpText>
        <label>Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IDN Solutions</fullName>
                </value>
                <value>
                    <fullName>Physicians</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Systems</fullName>
        <active>false</active>
        <businessProcess>R1 RCM Sales Process</businessProcess>
        <description>DEACTIVATED; IN R1 ONLY FOR HISTORICAL REFERENCE- Select to enter a Systems opportunity</description>
        <label>Systems</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ConQtr__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ConQtr</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Team</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Team.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HB</fullName>
    </customValue>
    <customValue>
        <fullName>OB-EMS</fullName>
    </customValue>
    <customValue>
        <fullName>Modular</fullName>
    </customValue>
    <masterLabel>Team</masterLabel>
</GlobalValueSet>

classes/testConsecutiveQuarterSales.cls
@isTEst
        private class testConsecutiveQuarterSales {
        
            @testSetup
            static void setup() {
                List<Opportunity> myOpp = new List<Opportunity>();
                Period per = new Period(StartDate = Date.newInstance(2020,1,1), EndDate = Date.newInstance(2020,3,31), Type = 'Quarter');
               
                Country__c usa = new Country__c(Name='United States', ISO_Code__c='US', ISO3_Code__c='USA');
                insert usa;
        
                User u = new User(FirstName = 'Test User', LastName = 'Tester', Team__c = 'HB',
                Username = '123@123646464646546546.com', Email = '123@gmail.com', Alias = 'Test', TimeZoneSidKey = 'GMT', 
                LocaleSidKey = 'en_US', EmailEncodingKey='ISO-8859-1',conqtr__c = 0,
                ProfileId ='00e41000001e0HOAAY', LanguageLocaleKey= 'en_US');
                insert u;
                
                Account a = new Account(Name = 'Penrod Health Care');
                a.BillingCountry = usa.ISO_Code__c;
                insert a;
                system.debug(a.name);
                Opportunity o1 = new Opportunity( Name = 'Penrod Health - E2E',
                                                 AccountId = a.Id,
                                                 StageName = 'Closed Won',
                                                 Amount = 20,
                                                 CloseDate = Date.newInstance(2020,2,1),
                                                 Vertical__c = 'IDN Solutions',
                                                 Target_Market__c = 'Hospitals and Health Systems',
                                                 Solution__c = 'Revenue Integrity Solutions ',
                                                 Duration__c = 60,
                                                 Type = 'New Business',
                                                 OwnerId = u.id,
                                                 Start_Date__c = Date.today());
                                                       
                   system.debug(o1.name);
                
                    myOpp.add(o1);
                    Opportunity o2 = new Opportunity( Name = 'Penrod Health - E2E',
                                                 AccountId = a.Id,
                                                 StageName = '1-Discover',
                                                 Amount = 10,
                                                 CloseDate = Date.newInstance(2020,3,1),
                                                 Vertical__c = 'IDN Solutions',
                                                 Target_Market__c = 'Hospitals and Health Systems',
                                                 Solution__c = 'Revenue Integrity Solutions ',
                                                 Duration__c = 60,
                                                 Type = 'New Business',
                                                 OwnerId=u.id,
                                                 
                                                 Start_Date__c = Date.today());
        
        
                        myOpp.add(o2);

                        insert myOpp;
                        system.debug('opps inserted =' +  myOpp.size());
                
            
                
            }
        
            @isTest
            static void validateClosed() {
               
           
                List<Opportunity> ClosedOpps = new List<Opportunity>();
                ClosedOpps =  [Select id from Opportunity where isclosed = true];
                System.assertEquals(1, closedopps.size(), 'There should only be 1 closed opportunity on insert.');
            
                
                
            }
            @isTest
            static void test2(){
                
           SchedulableContext sc = null;
     
         
            ConsecutiveQuarterSales ext = new ConsecutiveQuarterSales(); 
             ext.execute(sc);

         /*List<Period> recentQuarters = [
    SELECT quarterlabel, StartDate, EndDate 
    FROM Period
    WHERE endDate < today and Type = 'Quarter' 
    ORDER BY StartDate DESC limit 8];

                system.assertequals(8, recentquarters.size(),'how many qtrs');*/

            List<User> SalesUsers = new List<User>();
            SalesUsers =  [Select id, name from User where Team__c = 'HB' and conqtr__c = 1];
            
          

            for (user u : SalesUsers){
                system.debug(u.name);
            }
        
            system.assertEquals(1,SalesUsers.size(),'there should have been user with consec qtrs');
        
                    
            }
        }