objects/Account.object
<CustomObject>
    <fields>
        <fullName>Vertical__c</fullName>
        <inlineHelpText>Intermedix Market Segment</inlineHelpText>
        <label>Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Emergency 911</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Military</fullName>
                </value>
                <value>
                    <fullName>State/Local-Emergency Management</fullName>
                </value>
                <value>
                    <fullName>State/Local-Public Health</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>IDN</fullName>
                </value>
                <value>
                    <fullName>Physicians</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>ISO 3166 set of worldwide countries, and related ISO codes, used for address data consistency and integrity</description>
    <fields>
        <fullName>ISO3_Code__c</fullName>
        <description>ISO-3 code</description>
        <label>ISO3 Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>ISO-2 code</description>
        <label>ISO Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <defaultValue>IF( $RecordType.DeveloperName = "Enterprise" ,60, 
 IF ($RecordType.DeveloperName = "Modular",24,
12))</defaultValue>
        <inlineHelpText>Autopopulated based on Opp record Type but Opp owner can alter as needed. Enterprise: 60 mo, Modular: 24, Chart Audits &amp; Classes 1, All Others: 12.</inlineHelpText>
        <label>Contract Terms (Mo)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Milestone__c</fullName>
        <label>Sales Milestone</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Interest Generated</fullName>
                    <label>1.1 Interest Generated</label>
                </value>
                <value>
                    <fullName>Information Exchange Mtgs/Calls with additional buyers</fullName>
                    <label>1.2 Information Exchange Mtgs/Calls with additional buyers</label>
                </value>
                <value>
                    <fullName>Initial Understanding: Buyers/Problem/Funding/DRM</fullName>
                    <label>1.3 Initial Understanding: Buyers/Problem/Funding/DRM</label>
                </value>
                <value>
                    <fullName>Test Your Position (A trial walk on the deal)</fullName>
                    <label>1.4 Test Your Position (A trial walk on the deal)</label>
                </value>
                <value>
                    <fullName>RFP/ RFI received</fullName>
                    <label>1.5 RFP/ RFI received</label>
                </value>
                <value>
                    <fullName>1.6 Qualified Opportunity in the Pipeline</fullName>
                </value>
                <value>
                    <fullName>Review Opportunity with Manager (Mini Blue Sheet) and determine pursuit yes or no</fullName>
                    <label>1.7 Review Opportunity with Manager (Mini Blue Sheet) and determine pursuit yes or no</label>
                </value>
                <value>
                    <fullName>An R1 Message is Delivered</fullName>
                    <label>2.1 An R1 Message is Delivered</label>
                </value>
                <value>
                    <fullName>Buyer Identification and Access</fullName>
                    <label>2.2 Buyer Identification and Access</label>
                </value>
                <value>
                    <fullName>Identify and Begin to Develop a Coach(s)</fullName>
                    <label>2.3 Identify and Begin to Develop a Coach(s)</label>
                </value>
                <value>
                    <fullName>Link Clients Timeline to Date Related Motivation (DRM)</fullName>
                    <label>2.4 Link Clients Timeline to Date Related Motivation (DRM)</label>
                </value>
                <value>
                    <fullName>Confirm Funding and Legal Framework</fullName>
                    <label>2.5 Confirm Funding and Legal Framework</label>
                </value>
                <value>
                    <fullName>2.6 Gain agreement for customer to provide data</fullName>
                </value>
                <value>
                    <fullName>2.7 Identify Customer Alternatives to Solve</fullName>
                </value>
                <value>
                    <fullName>2.8 Create Blue Sheet</fullName>
                </value>
                <value>
                    <fullName>First Blue Sheet Session</fullName>
                    <label>2.9 First Blue Sheet Session</label>
                </value>
                <value>
                    <fullName>Deeper Dive(s) with Operations with Client</fullName>
                    <label>3.1 Deeper Dive(s) with Operations with Client</label>
                </value>
                <value>
                    <fullName>Operations and CSE define initial approach statement</fullName>
                    <label>3.2 Operations and CSE define initial approach statement</label>
                </value>
                <value>
                    <fullName>Put our Coach to work (may share approach with coach before you officially share with buyers)</fullName>
                    <label>3.3 Put our Coach to work (may share approach with coach before you officially share with buyers)</label>
                </value>
                <value>
                    <fullName>3.4 Gain Alignment of initial approach with coach(s)</fullName>
                </value>
                <value>
                    <fullName>Test our relative position:  Validate if the client's other alternatives to solve the problem are still viable?</fullName>
                    <label>3.5 Test our relative position:  Validate if the client's other alternatives to solve the problem are still viable?</label>
                </value>
                <value>
                    <fullName>3.6 Deployment Discussion</fullName>
                </value>
                <value>
                    <fullName>3.7 Produce Proposal/SOW/Proforma</fullName>
                </value>
                <value>
                    <fullName>3.8 Proforma Validation with Customer</fullName>
                </value>
                <value>
                    <fullName>3.9 Validate pricing per Internal Approval Guidelines</fullName>
                </value>
                <value>
                    <fullName>4.1 Present initial proposal/SOW/Proforma to Coach</fullName>
                </value>
                <value>
                    <fullName>4.2 Present initial proposal/SOW/Proforma</fullName>
                </value>
                <value>
                    <fullName>4.3 Identify Obstacles to being Vendor of Choice (VOC)</fullName>
                </value>
                <value>
                    <fullName>If necessary, arrange for reference call / site visit</fullName>
                    <label>4.3 If necessary, arrange for reference call / site visit</label>
                </value>
                <value>
                    <fullName>4.4 If necessary, arrange for reference call / site visit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <label>Solution</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Target_Market__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enterprise Revenue Cycle Mgmt Co-Managed Partnership</fullName>
                </value>
                <value>
                    <fullName>Enterprise Revenue Cycle Management Full Operating Partnership</fullName>
                </value>
                <value>
                    <fullName>Revenue Cycle Management Services OB</fullName>
                </value>
                <value>
                    <fullName>Practice Management Services</fullName>
                </value>
                <value>
                    <fullName>Optima Live</fullName>
                </value>
                <value>
                    <fullName>Optima Predict</fullName>
                </value>
                <value>
                    <fullName>TripTix</fullName>
                </value>
                <value>
                    <fullName>Revenue Integrity Solutions</fullName>
                </value>
                <value>
                    <fullName>Physician Advisory Solutions</fullName>
                </value>
                <value>
                    <fullName>Coding Management Solutions</fullName>
                </value>
                <value>
                    <fullName>Business Office Solutions</fullName>
                </value>
                <value>
                    <fullName>Anesthesia - Revenue Cycle Management Services</fullName>
                </value>
                <value>
                    <fullName>Anesthesia - Practice Management Services</fullName>
                </value>
                <value>
                    <fullName>Anesthesia - Coding Services</fullName>
                </value>
                <value>
                    <fullName>Hospital Medicine - Revenue Cycle Management Services</fullName>
                </value>
                <value>
                    <fullName>Hospital Medicine - Practice Management Services</fullName>
                </value>
                <value>
                    <fullName>Hospital Medicine - Coding Services</fullName>
                </value>
                <value>
                    <fullName>Emergency Medicine - Revenue Cycle Management Services</fullName>
                </value>
                <value>
                    <fullName>Emergency Medicine - Practice Management Services</fullName>
                </value>
                <value>
                    <fullName>Emergency Medicine - Coding Services</fullName>
                </value>
                <value>
                    <fullName>Revenue Cycle Management Services- EMS</fullName>
                </value>
                <value>
                    <fullName>Ambulance Supplemental Payment Program ASPP</fullName>
                </value>
                <value>
                    <fullName>Optima Managed Analytics Solutions</fullName>
                </value>
                <value>
                    <fullName>Optima Consulting Solutions</fullName>
                </value>
                <value>
                    <fullName>Clinical Documentation Improvement Solutions</fullName>
                </value>
                <value>
                    <fullName>Patient Experience Solutions</fullName>
                </value>
                <value>
                    <fullName>Patient Experience Technology</fullName>
                </value>
                <value>
                    <fullName>DatStat</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                    <isActive>false</isActive>
                    <label>Hybrid</label>
                </value>
                <value>
                    <fullName>Modular - Business Office Solutions</fullName>
                    <isActive>false</isActive>
                    <label>Modular - Business Office Solutions</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Anticipated start date when the customer will begin using R1 services or products.  This is important for revenue forecasting.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target_Market__c</fullName>
        <label>Target Market</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Vertical__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Hospitals and Health Systems</fullName>
                </value>
                <value>
                    <fullName>Office-Based Physicians</fullName>
                </value>
                <value>
                    <fullName>Hospital-Based Physicians</fullName>
                </value>
                <value>
                    <fullName>FD, Municipalities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <inlineHelpText>If left blank, will be set to the Account Vertical after saving. This is used in quote approval processes, so make sure it is accurate.</inlineHelpText>
        <label>Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IDN Solutions</fullName>
                </value>
                <value>
                    <fullName>Physicians</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Systems</fullName>
        <active>false</active>
        <businessProcess>R1 RCM Sales Process</businessProcess>
        <description>DEACTIVATED; IN R1 ONLY FOR HISTORICAL REFERENCE- Select to enter a Systems opportunity</description>
        <label>Systems</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_History__c.object
<CustomObject>
    <fields>
        <fullName>Exit_DateTime__c</fullName>
        <label>Exit DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <label>Exit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage_change__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stage change</label>
        <type>Checkbox</type>
    </fields>
    <label>Opportunity History</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Opportunity History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testOpportunityHandler.cls
@isTEst
private class testOpportunityHandler {

    @testSetup
    static void setup() {
        Country__c usa = new Country__c(Name='United States', ISO_Code__c='US', ISO3_Code__c='USA');
        insert usa;
        
        Account a = new Account(Name = 'Penrod Health Care');
        a.BillingCountry = usa.ISO_Code__c;
        insert a;
        
        Opportunity o = new Opportunity( Name = 'Penrod Health - E2E',
                                         AccountId = a.Id,
                                         StageName = '1-Discover',
                                         Amount = 1000000,
                                         CloseDate = Date.today(),
                                         Vertical__c = 'IDN Solutions',
                                         Target_Market__c = 'Hospitals and Health Systems',
                                         Solution__c = 'Revenue Integrity Solutions ',
                                         Duration__c = 60,
                                         Type = 'New Business',
                                         Start_Date__c = Date.today());
                                               
        insert o;
        system.debug('record type id is ' +(o.RecordTypeId));
    }

    @isTest
    static void validateNewHistory() {
        Opportunity o = getDefaultOpportunity();

        List<Opportunity_History__c> histories = getOpportunityHistoriesByOpportunityId(o.Id);
        
        System.assertEquals(1, histories.size(), 'There should only be 1 opportunity history on insert.');
        system.assertEquals(null, histories[0].Exit_Date__c, 'The exit date should be blank.');
        system.assertEquals(null, histories[0].Exit_DateTime__c, 'The exit datetime should be blank.');
        system.assertEquals(true, histories[0].Stage_change__c, 'The stage change checkbox should be true.');
        
        
    }
    @isTest
    static void opportunityUpdated_stageHistoryChanged_expectNoNewOpportunityHistoryRecordsTest() {
        Opportunity o = getDefaultOpportunity();

        
        List<Opportunity_History__c> histories = getOpportunityHistoriesByOpportunityId(o.Id);
        Integer historiesCountBeforeSalesMilestoneChange = histories.size();
       
        o.Sales_Milestone__c = 'Interest Generated';
        update o;
        
        histories = getOpportunityHistoriesByOpportunityId(o.Id);
        
        System.assertEquals(historiesCountBeforeSalesMilestoneChange, histories.size(), 'No new opportunity history records should be creatd when the sales milestone changes.');
    }
    @isTest
    static void validateUpdatedHistory() {
        Opportunity o = getDefaultOpportunity();

        o.StageName = '2-Qualify';
        
     
        update o;
        List<Opportunity_History__c> histories = getOpportunityHistoriesByOpportunityId(o.Id);
        
        System.assertEquals(2, histories.size(), 'There should be 2 opportunity histories when the stage name changes. One from the original insert and one from the stage change.');
        
        Opportunity_History__c firstHistory = histories[0];
        system.assertEquals(Date.Today(), firstHistory.Exit_Date__c, 'The exit date was not set on the original open opportunity history.');
       
    }

  
    
    static Opportunity getDefaultOpportunity() {
        return
        [SELECT Id,
                Name,
                AccountId,
                StageName,
                Sales_Milestone__c,
                Amount,
                CloseDate
           FROM Opportunity];
    }

    static List<Opportunity_History__c> getOpportunityHistoriesByOpportunityId(Id opportunityId) {
        return
        [SELECT Id,
                Name,
                Enter_Date__c,
                Exit_Date__c,
                Milestone__c,
                Stage_History__c,
                Exit_DateTime__c,
                Enter_DateTime__c,
                Stage_change__c,
                Amount__c
           FROM Opportunity_History__c
          WHERE Opportunity__c = :opportunityId
          ORDER By Name];
    }
}