objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
                <value>
                    <fullName>Closed Office / Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Competitive_Info__c.object
<CustomObject>
    <fields>
        <fullName>Competitor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor</label>
        <referenceTo>Competitor__c</referenceTo>
        <relationshipLabel>Competitive Info</relationshipLabel>
        <relationshipName>Competitive_Info</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OLDCompetitor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitive Info (Competitor)</relationshipLabel>
        <relationshipName>Competitive_Info1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <label>Related To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitive Info</relationshipLabel>
        <relationshipName>Competitive_Info</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Solution_Covered__c</fullName>
        <label>Solution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Solutions</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Competitive Info</label>
    <nameField>
        <displayFormat>CI-{000000}</displayFormat>
        <label>Competitive Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Competitor__c.object
<CustomObject>
    <label>Competitor</label>
    <nameField>
        <label>CompetitorName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>ISO 3166 set of worldwide countries, and related ISO codes, used for address data consistency and integrity</description>
    <fields>
        <fullName>ISO3_Code__c</fullName>
        <description>ISO-3 code</description>
        <label>ISO3 Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>ISO-2 code</description>
        <label>ISO Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Solutions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ambulance Supplemental Payment Program ASPP</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Business Office Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Documentation Improvement Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Coding Management Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Revenue Cycle Management Full Operating Partnership</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Revenue Cycle Mgmt Co-Managed Partnership</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Consulting Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Live</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Managed Analytics Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Predict</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Experience Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Physician Advisory Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Cycle Management Services- EMS</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Cycle Management Services OB</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Integrity Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>TripTix</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Experience Technology</fullName>
    </customValue>
    <customValue>
        <fullName>DatStat</fullName>
    </customValue>
    <masterLabel>Solutions</masterLabel>
</GlobalValueSet>

classes/CompetitiveInfoExtensionClass_TEST.cls
@isTest
private class CompetitiveInfoExtensionClass_TEST{
  
  static testmethod void myTestData(){
   

    
    Country__c usa = new Country__c(Name='United States', ISO_Code__c='US', ISO3_Code__c='USA');
    insert usa;
      
    Account a = new Account(Name = 'Penrod Health Care');
    a.BillingCountry = usa.ISO_Code__c;
    Insert a; 
      
    Competitor__c comp = new Competitor__c(name= 'Testcomp');
    insert comp;
    
   
    
    Competitive_Info__c obj = new Competitive_Info__c( Related_To__c = a.id, Competitor_name__c = comp.id, Solution_Covered__c = 'Triptix', Status__c='Active');
    insert obj;   
                                                      
      
      
    test.startTest();
      
    ApexPages.StandardController stdController = new ApexPages.StandardController(a);


    pagereference pageref = page.ComptInvoVFP2;
    pageref.getParameters().put('id',a.id);
    pageref.getParameters().put('Solution',obj.solution_covered__c);      
      
    Test.setCurrentPage(pageref);
      
      
      
      
      
    CompetitiveInfoExtensionClass obj01 = new CompetitiveInfoExtensionClass(stdcontroller);
    
     obj01.AccountID = a.ID;
     
      
    test.stopTest();
  }
}