objects/Account.object
<CustomObject>
    <fields>
        <fullName>Vertical__c</fullName>
        <inlineHelpText>Intermedix Market Segment</inlineHelpText>
        <label>Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Emergency 911</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Military</fullName>
                </value>
                <value>
                    <fullName>State/Local-Emergency Management</fullName>
                </value>
                <value>
                    <fullName>State/Local-Public Health</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>IDN</fullName>
                </value>
                <value>
                    <fullName>Physicians</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SolPort__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solution Portfolio</relationshipLabel>
        <relationshipName>SolPort</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group_By__c</fullName>
        <label>Group By</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SolutionID__c</fullName>
        <label>SolutionID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solution_Name__c</fullName>
        <label>Solution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Solutions</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Vertical</valueSetName>
        </valueSet>
    </fields>
    <label>Solution Portfolio</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>Solution Portfolio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution Portfolio</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Solution_Master__c.object
<CustomObject>
    <fields>
        <fullName>Group_By__c</fullName>
        <label>Group By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GroupBy</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <label>Solution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Solutions</valueSetName>
        </valueSet>
    </fields>
    <label>Solution Master</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Solution Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solutions Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/GroupBy.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HB</fullName>
    </customValue>
    <customValue>
        <fullName>OB</fullName>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
    </customValue>
    <customValue>
        <fullName>EMS</fullName>
    </customValue>
    <customValue>
        <fullName>MOD</fullName>
    </customValue>
    <customValue>
        <fullName>E2E</fullName>
    </customValue>
    <customValue>
        <fullName>OPT</fullName>
    </customValue>
    <masterLabel>GroupBy</masterLabel>
</GlobalValueSet>

globalValueSets/Solutions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ambulance Supplemental Payment Program ASPP</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Business Office Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Documentation Improvement Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Coding Management Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Revenue Cycle Management Full Operating Partnership</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Revenue Cycle Mgmt Co-Managed Partnership</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Consulting Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Live</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Managed Analytics Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Predict</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Experience Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Physician Advisory Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Cycle Management Services- EMS</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Cycle Management Services OB</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Integrity Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>TripTix</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Experience Technology</fullName>
    </customValue>
    <customValue>
        <fullName>DatStat</fullName>
    </customValue>
    <masterLabel>Solutions</masterLabel>
</GlobalValueSet>

globalValueSets/Vertical.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>EMS</fullName>
    </customValue>
    <customValue>
        <fullName>MOD</fullName>
    </customValue>
    <customValue>
        <fullName>OPT</fullName>
    </customValue>
    <customValue>
        <fullName>PHY</fullName>
    </customValue>
    <customValue>
        <fullName>PHY-OB-RCM</fullName>
        <isActive>false</isActive>
        <label>PHY-OB-RCM</label>
    </customValue>
    <customValue>
        <fullName>IDN</fullName>
        <isActive>false</isActive>
        <label>IDN</label>
    </customValue>
    <customValue>
        <fullName>PHY-HB-PM</fullName>
        <isActive>false</isActive>
        <label>PHY-HB-PM</label>
    </customValue>
    <customValue>
        <fullName>PHY-HB-COD</fullName>
        <isActive>false</isActive>
        <label>PHY-HB-COD</label>
    </customValue>
    <customValue>
        <fullName>PHY-OB-PM</fullName>
        <isActive>false</isActive>
        <label>PHY-OB-PM</label>
    </customValue>
    <customValue>
        <fullName>PHY-ED-RCM</fullName>
        <isActive>false</isActive>
        <label>PHY-ED-RCM</label>
    </customValue>
    <customValue>
        <fullName>PHY-HB-RCM</fullName>
        <isActive>false</isActive>
        <label>PHY-HB-RCM</label>
    </customValue>
    <masterLabel>Vertical</masterLabel>
</GlobalValueSet>

classes/AddSolutionPortfolio.cls
public class AddSolutionPortfolio {
@InvocableMethod

    public static void SPAssign(List<ID> ids) {
    
        
    List<Account> myAccs = [SELECT Id FROM Account where Id =:ids];
      system.debug('accounts selected were ' + myAccs.size());     
        //get a list of account ids 
        Set<Id> accIds = new Set<Id>();

    //create empty whitepsace list
           List<SolPort__c> SPList = new List<SolPort__c>();    
    
  //iterate thru list of valid accounts
            
for (Account a : myAccs){
                            
		
		//look for existing whitespace records for this account	 
		List<SolPort__c> solport = [
            SELECT SolutionID__c 
            FROM SolPort__c where account__c = :a.id
            ];
        system.debug('solutions portfolio list is' + solport.size());
        //get a list of solutions already exist for the account 

		Set<Id> UsedsolutionIds = new Set<Id>();
		
    	
    if(solport.size() != 0 ) { 
        for (SolPort__c c : solport){
		               
		UsedSolutionIds.add(c.SolutionID__c);
        }}
		
		system.debug('used ids are' + UsedSolutionIds.size());

//get solutions that don't already exist
		List<Solution_Master__c> sollist = [
            SELECT Id, Group_by__c, Solution__c
            FROM Solution_Master__c where id not in :UsedsolutionIds
            ];
        
        //create ws list record for each solution left in Sollist
			system.debug('valid solution count is' + sollist.size());
        
		for (Solution_Master__c sm: sollist){
		SolPort__c w = new SolPort__c();
           
        w.Account__c = a.Id;
		w.Group_By__c = sm.Group_by__c;
        w.Solution_Name__c = sm.Solution__c;
        w.SolutionID__c = sm.Id;
		SPlist.add(w);
       
        //new Whitespace__c(Vertical__c='IDN',Solution_Area__c='Business Office Solutions',Account__c=c.Id);
		}
       
            
       
                
            
               }
       

    
     // Bulk insert all ws records with one DML call
     // 
     // 
     try {
    
    	insert SPlist;
		} 
    catch(DmlException e) {
    System.debug('The following exception has occurred: ' + e.getMessage());
    }
    	system.debug('made it to end');
}
}