objects/Competitor__c.object
<CustomObject>
    <label>Competitor</label>
    <nameField>
        <label>CompetitorName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SolPort__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solution Portfolio</relationshipLabel>
        <relationshipName>SolPort</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Competitor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Competitors__c</fullName>
        <label>Competitors</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CountAllCompetitors__c</fullName>
        <defaultValue>0</defaultValue>
        <label>CountAllCompetitors</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Former__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Former</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_By__c</fullName>
        <label>Group By</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Indicator__c</fullName>
        <label>Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sold-Current</fullName>
                </value>
                <value>
                    <fullName>Sold-Former</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Target</fullName>
                </value>
                <value>
                    <fullName>Not a fit</fullName>
                </value>
                <value>
                    <fullName>Competitive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_value__c</fullName>
        <label>Opportunity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Closed Walked</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution_Fit__c</fullName>
        <label>Solution Fit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Undetermined</fullName>
                    <default>true</default>
                    <label>Undetermined</label>
                </value>
                <value>
                    <fullName>Target</fullName>
                </value>
                <value>
                    <fullName>Not a Fit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution_Name__c</fullName>
        <label>Solution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Solutions</valueSetName>
        </valueSet>
    </fields>
    <label>Solution Portfolio</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>Solution Portfolio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution Portfolio</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Solutions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ambulance Supplemental Payment Program ASPP</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Business Office Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Documentation Improvement Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Coding Management Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Revenue Cycle Management Full Operating Partnership</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Revenue Cycle Mgmt Co-Managed Partnership</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Coding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Medicine - Revenue Cycle Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Consulting Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Live</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Managed Analytics Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Optima Predict</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Experience Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Physician Advisory Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Practice Management Services</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Cycle Management Services- EMS</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Cycle Management Services OB</fullName>
    </customValue>
    <customValue>
        <fullName>Revenue Integrity Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>TripTix</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Experience Technology</fullName>
    </customValue>
    <customValue>
        <fullName>DatStat</fullName>
    </customValue>
    <masterLabel>Solutions</masterLabel>
</GlobalValueSet>

classes/SolPortcls.cls
public class SolPortcls {

public String groupFieldName {get; set;}    
public SolPort__c[] SPList{get;set;}
public List<GroupWrapper> groups {get; set;}  
String SPId;


public void setSPId(String val)
{
this.SPId=val;
}
public String getSPId()
{
return this.SPId;
}
public PageReference EditSolPort()
    {

        String mySPId = getSpid();
        PageReference pageRef= new PageReference('/'+ mySPId +'/e');
		system.debug('editsolport was called');
        system.debug(mySPId);
        pageRef.setredirect(true);

        return pageRef;

    }
    
    

 
    


     
    public solportcls(ApexPages.standardController std){
        SPList=new Solport__c[]{};
        groupFieldName='Group_By__c';
         string AccountID=ApexPages.currentPage().getParameters().get('id');
        if(AccountID==NULL){
            system.debug('No Id available');
        }
        else{
            
            Account[] CWS=new Account[]{};
            CWS=[Select id,(select Group_By__c, Solution_Name__c, Indicator__c,  Opportunity_value__c, Solution_fit__c, competitor__c, CountAllCompetitors__c, Competitors__c, current__c, former__c from SolPort__r Order by Group_By__c, Solution_Name__c)  from Account where id =:AccountID ];
            for( Account c:CWS ){
                for(SolPort__c obj:c.Solport__r){
                    SPList.add(obj);
                }
                
                setupGrouping();
            }
        }
    }
    
    private void setupGrouping()
 {
  Map<String, List<SolPort__c>> groupedMap=new Map<String, List<SolPort__c>>();
  for (SolPort__c acc : spList)
  {
   String key=String.valueof(acc.get('Group_By__c'));
      system.debug(key);
   if ( (null==key) || (0==key.length()) )
   {
    key='Undefined';
   }
   List<SolPort__c> groupedAccs=groupedMap.get(key);
   if (null==groupedAccs)
   {
    groupedAccs=new List<SolPort__c>();
    groupedMap.put(key, groupedAccs);
   }
    
   groupedAccs.add(acc);
     system.debug('grouped accs' + key + 'size is' + groupedaccs.size());                                
  }
     
   
  groups=new List<GroupWrapper>();
  for (String key : groupedMap.keySet())
  {
   GroupWrapper gr=new GroupWrapper();
   groups.add(gr);
   gr.accs=groupedMap.get(key);
   gr.groupedVal=key;
  }
 }
    
    
    
    public class GroupWrapper
{
 	public List<SolPort__c> accs {get; set;}
 	public String groupedVal {get; set;}
 	
}
}