objects/Competitor__c.object
<CustomObject>
    <label>Competitor</label>
    <nameField>
        <label>CompetitorName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>ISO 3166 set of worldwide countries, and related ISO codes, used for address data consistency and integrity</description>
    <fields>
        <fullName>ISO3_Code__c</fullName>
        <description>ISO-3 code</description>
        <label>ISO3 Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>ISO-2 code</description>
        <label>ISO Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SolPort__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solution Portfolio</relationshipLabel>
        <relationshipName>SolPort</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Competitor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Former__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Former</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_By__c</fullName>
        <label>Group By</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Not_a_Fit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Not a Fit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Target</label>
        <type>Checkbox</type>
    </fields>
    <label>Solution Portfolio</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>Solution Portfolio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution Portfolio</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SolPortcls_Test.cls
@isTest
private class SolPortcls_Test{
  
  static testmethod void myTestData(){
   

    
    Country__c usa = new Country__c(Name='United States', ISO_Code__c='US', ISO3_Code__c='USA');
    insert usa;
      
    Account a = new Account(Name = 'Penrod Health Care');
    a.BillingCountry = usa.ISO_Code__c;
    Insert a; 
    
    SolPort__c solport_Obj = new SolPort__c(Account__c = a.id, Opportunity__c = false, Not_a_Fit__c = false, Competitor__c = false, Target__c = false, Current__c = false, Former__c = false);
    Insert solport_Obj; 
      
    test.startTest();
      
    ApexPages.StandardController stdController = new ApexPages.StandardController(a);


    pagereference pageref = page.SolPortGroupedvfp;
    pageref.getParameters().put('id',a.id);
           
      
    Test.setCurrentPage(pageref);
    SolPortcls obj01 = new SolPortcls(stdcontroller);
    obj01.groupFieldName = 'Group_By__c';
    obj01.setSPId(solport_obj.id);
    obj01.SPList = new SolPort__c[1];
    obj01.groups = new List<SolPortcls.GroupWrapper>();
    obj01.setSPId('test data');
   
      
    obj01.EditSolPort();
      
       

    

      
    test.stopTest();
  }
}