objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AccountText__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccountText</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <description>From lead. open text. not really used by anyone but good for historical purposes. 1/5/19 MAlterio</description>
        <label>Lead Source Detail</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TaskContactController3.cls
public with sharing class TaskContactController3 {

	public String ApexContactID {
		get {
			if (ApexContactID == null) {
				ApexContactID = ApexPages.currentPage().getParameters().get('WhoID');
			}
			return ApexContactID;
		}
		set;
	}
	public Contact c {
		get {
			if (c == null) {
				c = [SELECT ID, Name, AccountText__c, Phone, Email, LeadSource, Lead_Source_Detail__c FROM Contact WHERE id = :ApexContactID];
			}
			return c; 
		}
		set;
	}
}