objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Event_Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>zzzEvent Attended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Registered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>zzzEvent Registered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Marketing_qualified_lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marketing qualified lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Longer_with_Company__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this if the contact is no longer with this company.  Set up new contact on the new company, DO NOT change existing contact to 'move' it to the new company as this will alter the activities.</inlineHelpText>
        <label>No Longer with Company</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Call_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates that a Sales Call has been requested. Typically via a form. Activity will be created and assigned to the contact owner.</inlineHelpText>
        <label>Sales Call Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VIP</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>ISO 3166 set of worldwide countries, and related ISO codes, used for address data consistency and integrity</description>
    <fields>
        <fullName>ISO3_Code__c</fullName>
        <description>ISO-3 code</description>
        <label>ISO3 Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>ISO-2 code</description>
        <label>ISO Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CandidateContactExtensionTest.cls
@isTest
private class CandidateContactExtensionTest{
   static testmethod void myTestData(){
   
      
      Country__c usa = new Country__c(Name='United States', ISO_Code__c='US', ISO3_Code__c='USA');
        insert usa;
        
        Account a = new Account(Name = 'Penrod Health Care');
        a.BillingCountry = usa.ISO_Code__c;
        insert a;
    
 
    Contact contact_Obj = new Contact(AccountId = a.id, LastName = 'LastName291', FirstName = 'First683', Salutation = 'Mr.', RecordTypeId = '01241000001QHOqAAO',MailingStreet = 'PratapNagar', MailingCity = 'Jaipur', MailingState = 'Raj', MailingPostalCode = '302022', MailingCountry = usa.ISO_Code__c, Phone = '54343-89064', Email = 'Email38@test.com', HasOptedOutOfEmail = false, HasOptedOutOfFax = false, DoNotCall = false, texcellency__DefHC_Is_Active__c = false, VIP__c = false, pi__Needs_Score_Synced__c = false, pi__pardot_hard_bounced__c = false, Event_Registered__c = false, Event_Attended__c = false, No_Longer_with_Company__c = false, Sales_Call_Requested__c = false, Marketing_qualified_lead__c = false);
    Insert contact_Obj; 
     test.startTest();
    ApexPages.StandardController stdController = new ApexPages.StandardController(contact_Obj);
	CandidateContactExtension ext = new CandidateContactExtension(stdController);
    ext.saveCandidate();
	
       
     
     PageReference pty = Page.CandidateThankyou;
     Test.setCurrentPage(pty);
     system.debug(pty.geturl());
     system.assertEquals(pty.geturl(),'/apex/candidatethankyou','pagenotfound');
       
       
     test.stopTest(); 

    
 
  }
}