objects/Country__c.object
<CustomObject>
    <description>ISO 3166 set of worldwide countries, and related ISO codes, used for address data consistency and integrity</description>
    <fields>
        <fullName>ISO3_Code__c</fullName>
        <description>ISO-3 code</description>
        <label>ISO3 Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>ISO-2 code</description>
        <label>ISO Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>POI_for_Opp_Conversion__c</fullName>
        <label>POI for Opp Conversion</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_of_Interest_POI__c</fullName>
        <description>This is the akin to the Opportunity's third tier in the 4 layer logic: Vertical, Target, Solution, Services. This POI field gets mapped to the Opportunity's "POI for Opp Conversion" field. And mapped to the Contact.</description>
        <inlineHelpText>Product(s) of Interest. Either assumed based on activity or self proclaimed initially. Sales can and will modify throughout the funnel stages.</inlineHelpText>
        <label>Product(s) of Interest (POI)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IDN-RCM-Full Operating</fullName>
                </value>
                <value>
                    <fullName>IDN-RCM-CoManaged</fullName>
                </value>
                <value>
                    <fullName>IDN-Patient Access</fullName>
                </value>
                <value>
                    <fullName>IDN-Revenue Integrity</fullName>
                </value>
                <value>
                    <fullName>IDN-Physician Advisory</fullName>
                </value>
                <value>
                    <fullName>IDN-Coding Management</fullName>
                </value>
                <value>
                    <fullName>IDN-Business Office</fullName>
                </value>
                <value>
                    <fullName>OfficeBased-RCM</fullName>
                </value>
                <value>
                    <fullName>OfficeBased-PM</fullName>
                </value>
                <value>
                    <fullName>Anesthesia-RCM</fullName>
                </value>
                <value>
                    <fullName>Anesthesia-PM</fullName>
                </value>
                <value>
                    <fullName>Anesthesia-Coding</fullName>
                </value>
                <value>
                    <fullName>Hospital Med-RCM</fullName>
                </value>
                <value>
                    <fullName>Hospital Med-PM</fullName>
                </value>
                <value>
                    <fullName>Hospital Med-Coding</fullName>
                </value>
                <value>
                    <fullName>Emergency Med-RCM</fullName>
                </value>
                <value>
                    <fullName>Emergency Med-PM</fullName>
                </value>
                <value>
                    <fullName>Emergency Med-Coding</fullName>
                </value>
                <value>
                    <fullName>EMS-RCM</fullName>
                </value>
                <value>
                    <fullName>EMS-Optima Live</fullName>
                </value>
                <value>
                    <fullName>EMS-Optima Predict</fullName>
                </value>
                <value>
                    <fullName>EMS-TripTix</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LeadTriggerHandlerClassTest.cls
@isTest
public with sharing class LeadTriggerHandlerClassTest {
    private static final String USA_FULL_NAME = 'United States';
    
    @testSetup
    static void testSetup() {
        Country__c usa = new Country__c(Name = USA_FULL_NAME, ISO_Code__c='US', ISO3_Code__c='USA');
        insert usa;
    }
    
    @isTest
    static void newLead_productOfInterestEmpty_expectPOIForOpportunityEmptyTest() {
        Lead newLead = buildLead();
        newLead.Product_of_Interest_POI__c = null;

        insert newLead;

        assertPOIForOppConversionBlank(newLead.Id);
    }

    @isTest
    static void newLead_productOfInterestPopulated_expectPOIForOpportunityPopulatedTest() {
        Lead newLead = buildLead();
        
        String productOfInterest = getFirstValidProductOfInterestPicklistValue();
        newLead.Product_of_Interest_POI__c = productOfInterest;

        insert newLead;

        assertPOIForOppConversionContains(productOfInterest, newLead.Id);
    }
    
    @isTest
    static void updateLead_productOfInterestPopulated_expectPOIForOpportunityPopulatedTest() {
        Lead newLead = buildLead();
        insert newLead;
        
        assertPOIForOppConversionBlank(newLead.Id);

        String productOfInterest = getFirstValidProductOfInterestPicklistValue();
        newLead.Product_of_Interest_POI__c = productOfInterest;

        update newLead;

        assertPOIForOppConversionContains(productOfInterest, newLead.Id);
    }

    @isTest
    static void updateLead_productOfInterestEmptied_expectPOIForOpportunityEmptiedTest() {
        Lead newLead = buildLead();
        
        String productOfInterest = getFirstValidProductOfInterestPicklistValue();
        newLead.Product_of_Interest_POI__c = productOfInterest;
        
        insert newLead;
        
        assertPOIForOppConversionContains(productOfInterest, newLead.Id);

        newLead.Product_of_Interest_POI__c = null;
        update newLead;

        assertPOIForOppConversionBlank(newLead.Id);
    }
    
    static Lead buildLead() {
        Lead newLead = new Lead();

        newLead.LastName = 'Test';
        newLead.Country = USA_FULL_NAME;
        newLead.Company = 'Test Company';

        return newLead;
    }
    
    static Lead getLeadById(Id leadId) {
        return
        [SELECT Id,
                Name,
                Product_of_Interest_POI__c,
                POI_for_Opp_Conversion__c
           FROM Lead
          WHERE Id = :leadId];
    }
    
    static void assertPOIForOppConversionBlank(Id leadId) {
        Lead l = getLeadById(leadId);
        
        system.assert(String.isBlank(l.POI_for_Opp_Conversion__c), 'The POI for Opp Conversion is not blank. Value: ' + l.POI_for_Opp_Conversion__c);
    }
    
    static void assertPOIForOppConversionContains(String expectedProductOfInterest, Id leadId) {
        Lead l = getLeadById(leadId);
        
        system.assert(String.isNotBlank(l.POI_for_Opp_Conversion__c), 'The POI for Opp Conversion is blank and should not be.');
        system.assert(l.POI_for_Opp_Conversion__c.contains(expectedProductOfInterest), 'The POI for Opp Conversion does not contain "' + expectedProductOfInterest + '"');
    }
    
    static String getFirstValidProductOfInterestPicklistValue() {
        Schema.DescribeFieldResult fieldResult = Lead.Product_of_Interest_POI__c.getDescribe();
        List<Schema.PicklistEntry> ples = fieldResult.getPicklistValues();

        for( Schema.PicklistEntry picklistVal : ples){
            if (picklistVal.isActive()) {
                return picklistVal.getValue();
            }
        }
        
        return '';
    }
}