objects/Country__c.object
<CustomObject>
    <description>ISO 3166 set of worldwide countries, and related ISO codes, used for address data consistency and integrity</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>POI_for_Opp_Conversion__c</fullName>
        <label>POI for Opp Conversion</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_of_Interest_POI__c</fullName>
        <description>This is the akin to the Opportunity's third tier in the 4 layer logic: Vertical, Target, Solution, Services. This POI field gets mapped to the Opportunity's "POI for Opp Conversion" field. And mapped to the Contact.</description>
        <inlineHelpText>Product(s) of Interest. Either assumed based on activity or self proclaimed initially. Sales can and will modify throughout the funnel stages.</inlineHelpText>
        <label>Product(s) of Interest (POI)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IDN-RCM-Full Operating</fullName>
                </value>
                <value>
                    <fullName>IDN-RCM-CoManaged</fullName>
                </value>
                <value>
                    <fullName>IDN-Patient Access</fullName>
                </value>
                <value>
                    <fullName>IDN-Revenue Integrity</fullName>
                </value>
                <value>
                    <fullName>IDN-Physician Advisory</fullName>
                </value>
                <value>
                    <fullName>IDN-Coding Management</fullName>
                </value>
                <value>
                    <fullName>IDN-Business Office</fullName>
                </value>
                <value>
                    <fullName>OfficeBased-RCM</fullName>
                </value>
                <value>
                    <fullName>OfficeBased-PM</fullName>
                </value>
                <value>
                    <fullName>Anesthesia-RCM</fullName>
                </value>
                <value>
                    <fullName>Anesthesia-PM</fullName>
                </value>
                <value>
                    <fullName>Anesthesia-Coding</fullName>
                </value>
                <value>
                    <fullName>Hospital Med-RCM</fullName>
                </value>
                <value>
                    <fullName>Hospital Med-PM</fullName>
                </value>
                <value>
                    <fullName>Hospital Med-Coding</fullName>
                </value>
                <value>
                    <fullName>Emergency Med-RCM</fullName>
                </value>
                <value>
                    <fullName>Emergency Med-PM</fullName>
                </value>
                <value>
                    <fullName>Emergency Med-Coding</fullName>
                </value>
                <value>
                    <fullName>EMS-RCM</fullName>
                </value>
                <value>
                    <fullName>EMS-Optima Live</fullName>
                </value>
                <value>
                    <fullName>EMS-Optima Predict</fullName>
                </value>
                <value>
                    <fullName>EMS-TripTix</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/StateProvince__c.object
<CustomObject>
    <description>Set of states/provinces by country used for address data consistency and integrity</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States/Provinces</relationshipLabel>
        <relationshipName>StatesProvinces</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>State/Province</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States/Provinces</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LeadTriggerHandlerClass.cls
/*	LeadTriggerHandlerClass
	2018-11-06 revisions: Gary Triassi (gtriassi@trigon-group.com)
	
	Called By:	ContactTriggerHandler.trigger
	
	Purpose:
	-	before delete:
		o	 
	-	before insert:
		o	Geographic field (Country, State, Super Region) validation and attribution
	- 	before update:
		o	Geographic field (Country, State, Super Region) validation and attribution
	-	after insert:
		o	
	-	after update:
		o	
*/
	
public class LeadTriggerHandlerClass {
	//public variables
    
    //private variables
    
   	//geo (Country and State) maps
    private map<String, Country__c> countriesMapByName = new map<String, Country__c>();
    private map<String, Country__c> countriesMapByISO2 = new map<String, Country__c>();
    private map<String, Country__c> countriesMapByISO3 = new map<String, Country__c>();
	private map<String, StateProvince__c> statesMapByCode = new map<String, StateProvince__c>();
	private map<String, StateProvince__c> statesMapByName = new map<String, StateProvince__c>();
	private map<String, StateProvince__c> statesMapByAlt = new map<String, StateProvince__c>();
	private set<String> countries2Check = new set<String>();
       
    public LeadTriggerHandlerClass(){
		      	
    }//end LeadTriggerHandlerClass()

    public void afterInsert(list<Lead> leadList){      	 
	
    }//end afterInsert()
    
    public void afterUpdate(list<Lead> leadList, map<Id, Lead> oldLeadMap){

  	}//end afterUpdate()
  	
  	public void beforeDelete(map<Id, Lead> oldLeadMap){

  	}//end beforeDelete  

    public void beforeInsert(list<Lead> leadList){ 
      	//cycle inbound Lead records once in order to initialize collections
      	Boolean addressChange = false;
      	for (Lead thisLead:leadList){
        	//check for Address related data
        	if(thisLead.Street!=null|| thisLead.City!=null || thisLead.State!=null || thisLead.PostalCode!=null || thisLead.Country!=null){
        		//identify that an address change has occurred for related geo map loads
        		addressChange = true;
        	}        
      	}//end initial inbound Lead cycle
       		
   		//load geo (Country and State) if necessary
   		if(addressChange){
	    	CommonMethods.loadCountryMaps(countriesMapByName, countriesMapByISO2, countriesMapByISO3);
			CommonMethods.loadStatesMaps(statesMapByCode, statesMapByName, statesMapByAlt, countries2Check);
   		}    	      	    	
    
    	//cycle inbound Leads a second time updating data
      	for (Lead thisLead:leadList){
      		Boolean goodGeo = false;
      		if(!addressChange){goodGeo=true;}
      		else{
      			goodGeo = CommonMethods.geoFieldsValidation(0, thisLead, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
      														statesMapByName, statesMapByAlt, countries2Check, false);
      		}
      		if(goodGeo){
	        	 
      		}
      	}//end of second inbound Lead cycle
      	
      	copyProductOfInterestToTextField(leadList);   	
      	
    }//end beforeInsert()   

    public void beforeUpdate(map<Id, Lead> newContMap, map<Id, Lead> oldLeadMap){
      	//cycle inbound Lead records once in order to initialize collections
      	Boolean addressChange = false;
      	map<Id, Lead> contactMap = new map<Id, Lead>();
      	for (Lead thisLead:newContMap.values()){
      		Lead oldLead = oldLeadMap.get(thisLead.Id);
        	//check for Address related changes
        	if(thisLead.Street!=oldLead.Street || thisLead.City!=oldLead.City || thisLead.State!=oldLead.State || 
        		thisLead.PostalCode!=oldLead.PostalCode || thisLead.Country!=oldLead.Country){
        		//identify that an address change has occurred for related geo map loads
        		addressChange = true;
        	} 
      	}//end of 1st inbound Lead cycle
      	
   		//load geo (Country and State) maps if necessary
   		if(addressChange){
	    	CommonMethods.loadCountryMaps(countriesMapByName, countriesMapByISO2, countriesMapByISO3);
			CommonMethods.loadStatesMaps(statesMapByCode, statesMapByName, statesMapByAlt, countries2Check);
   		}
   		
      	//cycle inbound Leads for a 2nd time updating data and triggering actions   	
      	for (Lead thisLead:newContMap.values()){
        	Lead oldLead = oldLeadMap.get(thisLead.Id);
      		Boolean goodGeo = false;
      		if(!addressChange){goodGeo=true;}
      		else{
      			goodGeo = CommonMethods.geoFieldsValidation(0, thisLead, countriesMapByName, countriesMapByISO2, countriesMapByISO3, statesMapByCode, 
      														statesMapByName, statesMapByAlt, countries2Check, false);
      		}
      		if(goodGeo){
	        	 
      		}//end good geo logic
        	
  		}//end of 2nd inbound Lead cycle

  		copyProductOfInterestToTextField(newContMap.values());
  		
    }//end beforeUpdate()
    
    private void copyProductOfInterestToTextField(List<Lead> leads) {
        for (Lead l : leads) {
            l.POI_for_Opp_Conversion__c = l.Product_of_Interest_POI__c;
        }
    }
    
}//end LeadTriggerHandlerClass()