objects/Country__c.object
<CustomObject>
    <description>ISO 3166 set of worldwide countries, and related ISO codes, used for address data consistency and integrity</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/IMX_Contract__c.object
<CustomObject>
    <description>CUSTOM OBJECT FORMERLY LABELLED "IMX CONTRACT"; NOT THE SAME AS THE NATIVE CONTRACT OBJECT</description>
    <fields>
        <fullName>Inflation_Since_Annual_Increase__c</fullName>
        <description>This field can't be set to read-only because the Apex code that updates it won't be able to run</description>
        <label>Inflation Since Annual Increase</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Inflation_Since_Hourly_Increase__c</fullName>
        <description>This field can't be set to read-only because the Apex code that updates it won't be able to run</description>
        <label>Inflation Since Hourly Increase</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <recordTypes>
        <fullName>Optima_Contract</fullName>
        <active>true</active>
        <label>Optima Contract</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Inflation__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>This must match up with the inflation country field on the IMX contract. It should be a picklist here, but salesforce makes it virtually impossible (or even actually impossible) to change field types once they are used in apex code so it has to be left as a text field</description>
        <label>Country</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Percentage__c</fullName>
        <label>Percentage</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inflation</label>
    <nameField>
        <displayFormat>I-{00}</displayFormat>
        <label>Inflation Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inflation</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OptimaInflationTester.cls
/***********************************************************************************************
 * Name:
 * Optima Inflation Tester
 * 
 * Author:
 * Jeff Arwady | Senior Consultant
 * akaCRM
 * and
 * Amanda Day | Operations Manager
 * Optima
 * 
 * Description:
 * This test class uses a method called inflTest() to create a test Account, IMX Contract,
 * and Inflation data. It simulates the JavaScript button by calling the OptimaInflation Global 
 * Class.  It then checks to make sure that the correct inflation calculations were done
 * *********************************************************************************************/

@isTest

private class OptimaInflationTester {
    @testSetup
    static void testSetup() {
        OptimaCountryTestData.Instance.insertCountry();
    }

    //============================================================================================
    static testMethod void inflTest1() {
    //============================================================================================
	//Check that the correct inflation values are used in the calculation
        
        List<Inflation__c> inflation = new List<Inflation__c>();    
        
		//Get record type to use below        
		RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'IMX_Contract__c' AND DeveloperName = 'Optima_Contract'];

        //Create Test Records
        
        //Insert Test Account
        Account a = OptimaAccountTestData.Instance.withOptimaCustomerCode('CUST1')
	                                              .insertAccount();
        
        //Insert Test IMX Contract
        IMX_Contract__c con = OptimaContractTestData.Instance.withAccountId(a.Id)
            												 .withInflationCountry('XX')
            												 .withLatestAnnualDate(date.parse('01/01/2013'))
            												 .withLatestHourlyDate(date.parse('01/01/2011'))
            												 .insertContract();

        //Insert inflation data
        
        //1. Too early - should not be used in any calculations
        {
        Inflation__c infl = new Inflation__c();
        infl.Country__c = 'XX';
        infl.Year__c = 2010;
        infl.Percentage__c = 1.1;
        inflation.add(infl);
        }    

        //2. Should only be used in hourly calculation
        {
        Inflation__c infl = new Inflation__c();
        infl.Country__c = 'XX';
        infl.Year__c = 2011;
        infl.Percentage__c = 2.2;
        inflation.add(infl);
        }
        
        //3. Should only be used in hourly calculation
        {
        Inflation__c infl = new Inflation__c();
        infl.Country__c = 'XX';
        infl.Year__c = 2012;
        infl.Percentage__c = 3.3;
        inflation.add(infl);
        }
        
        //4. Should be used in annual and hourly calculations
        {
        Inflation__c infl = new Inflation__c();
        infl.Country__c = 'XX';
        infl.Year__c = 2013;
        infl.Percentage__c = 4.4;
        inflation.add(infl);
        }
        
        //5. Should be used in annual and hourly calculations
        {
        Inflation__c infl = new Inflation__c();
        infl.Country__c = 'XX';
        infl.Year__c = 2014;
        infl.Percentage__c = 5.5;
        inflation.add(infl);
        }
        
        //6. Wrong country - should not be used in any calculations
        {
        Inflation__c infl = new Inflation__c();
        infl.Country__c = 'AA';
        infl.Year__c = 2014;
        infl.Percentage__c = 9.9;
        inflation.add(infl);
        }
        
        insert inflation;
            
        //Initiate Testing Procedure
        Test.startTest();
        
        OptimaInflation.inflation();
        
        Test.stopTest();
        
        //Initiate Verification Procedure
        con = [SELECT Id, Inflation_Since_Annual_Increase__c, Inflation_Since_Hourly_Increase__c 
               FROM IMX_Contract__c WHERE Id = :con.Id];

        //Assert that the correct values were calculated
        System.assertEquals(10.1, con.Inflation_Since_Annual_Increase__c);
        System.assertEquals(16.3, con.Inflation_Since_Hourly_Increase__c);        
    }
    
    //============================================================================================   
    static testMethod void inflTest2() {
    //============================================================================================
	//Check that inflation is set to null if there is no fee history
        
        List<Inflation__c> inflation = new List<Inflation__c>();    
        
		//Get record type to use below        
		RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'IMX_Contract__c' AND DeveloperName = 'Optima_Contract'];

        //Create Test Records
        
        //Insert Test Account
        Account a = OptimaAccountTestData.Instance.withOptimaCustomerCode('CUST1')
	                                              .insertAccount();
        
        //Insert Test IMX Contract with no fee history
        IMX_Contract__c con = OptimaContractTestData.Instance.withAccountId(a.Id)
            												 .withInflationCountry('XX')
            												 .withLatestAnnualDate(null)
            												 .withLatestHourlyDate(null)
            												 .insertContract();
        
        //Insert inflation data
        {
        Inflation__c infl = new Inflation__c();
        infl.Country__c = 'XX';
        infl.Year__c = 2014;
        infl.Percentage__c = 1.1;
        inflation.add(infl);
        }    
        
        insert inflation;
            
        //Initiate Testing Procedure
        Test.startTest();
        
        OptimaInflation.inflation();
        
        Test.stopTest();
        
        //Initiate Verification Procedure
        con = [SELECT Id, Inflation_Since_Annual_Increase__c, Inflation_Since_Hourly_Increase__c 
               FROM IMX_Contract__c WHERE Id = :con.Id];

        //Assert that the correct values were calculated
        System.assertEquals(null, con.Inflation_Since_Annual_Increase__c);
        System.assertEquals(null, con.Inflation_Since_Hourly_Increase__c);        
    }
}