objects/Fee_History__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fee_History__c</fullName>
        <displayFormat>FH-{00000}</displayFormat>
        <label>Fee History #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Hourly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Contract__c</fullName>
        <label>IMX Contract</label>
        <referenceTo>IMX_Contract__c</referenceTo>
        <relationshipLabel>Fee History</relationshipLabel>
        <relationshipName>Fee_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fee History</label>
    <nameField>
        <displayFormat>FH-{0000}</displayFormat>
        <label>Fee Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IMX_Contract__c.object
<CustomObject>
    <description>CUSTOM OBJECT FORMERLY LABELLED "IMX CONTRACT"; NOT THE SAME AS THE NATIVE CONTRACT OBJECT</description>
    <fields>
        <fullName>Latest_Annual_Fee_History_Amount__c</fullName>
        <description>This field can't be set to read-only, because the workflow rules and code that update it won't be able to run</description>
        <label>Latest Annual Fee History Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Latest_Annual_Fee_History_Date__c</fullName>
        <description>This field can't be set to read-only because the workflow rules and code that update it won't be able to run</description>
        <label>Latest Annual Fee History Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Latest_Hourly_Fee_History_Amount__c</fullName>
        <description>This field can't be set to read-only, because the workflow rules and code that update it won't be able to run</description>
        <label>Latest Hourly Fee History Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Latest_Hourly_Fee_History_Date__c</fullName>
        <description>This field can't be set to read-only because the workflow rules and code that update it won't be able to run</description>
        <label>Latest Hourly Fee History Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Invoice_Date__c</fullName>
        <description>This field can't be set to read-only because the Apex code that updates it won't be able to run</description>
        <label>Next Invoice Date</label>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Optima_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Master_Contract__c</fullName>
        <label>Master Contract</label>
        <referenceTo>IMX_Contract__c</referenceTo>
        <relationshipLabel>Optima Invoices</relationshipLabel>
        <relationshipName>Optima_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Optima Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Optima Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OptimaFeeHistoryTester.cls
/***********************************************************************************************
 * Name:
 * Optima Fee History Tester
 * 
 * Author:
 * Amanda Day
 * Optima
 * 
 * Description:
 * This test class uses a method called feeTest() to create test Account, IMX Contract,
 * Optima Invoice and Fee History data. It simulates the JavaScript button by calling the 
 * OptimaFeeHistory Global Class.  It then checks to make sure that the correct updates were 
 * made to the contract.
 * *********************************************************************************************/

@isTest

public class OptimaFeeHistoryTester {
    @testSetup
    static void testSetup() {
        OptimaCountryTestData.Instance.insertCountry();
    }

    static testMethod void feeTest() {

        //Create Test Records
        
        //Insert Test Account
        Account a = OptimaAccountTestData.Instance.withOptimaCustomerCode('CUST1')
                                            	  .insertAccount();
        
        //Insert Test Contracts
        IMX_Contract__c con = OptimaContractTestData.Instance.withAccountId(a.Id)
            												 .insertContract();
        IMX_Contract__c con2 = OptimaContractTestData.Instance.withAccountId(a.Id)
            												  .insertContract();

        //Insert invoices and fee history. By default invoices will be created for $100,000 and dated tomorrow
        //1. All fields should be updated as expected
        {
        	Optima_Invoice__c inv = OptimaInvoiceTestData.Instance.withContract(con.Id)
                												  .withDate(system.today().addDays(-1))
            													  .insertInvoice();
        }
        {
        	Optima_Invoice__c inv = OptimaInvoiceTestData.Instance.withContract(con.Id)
            													  .insertInvoice();
        }
        {
        	Optima_Invoice__c inv = OptimaInvoiceTestData.Instance.withContract(con.Id)
                												  .withDate(system.today().addDays(10))
            													  .insertInvoice();
        }
        
        {
        	Fee_History__c fee = new Fee_History__c();
        	fee.Master_Contract__c = con.Id;
        	fee.Amount__c = 100000;
        	fee.Effective_Date__c = system.today().addDays(-1);
            fee.Fee_Type__c = 'Annual';
        	insert fee;
        }
        {
        	Fee_History__c fee = new Fee_History__c();
        	fee.Master_Contract__c = con.Id;
        	fee.Amount__c = 200000;
        	fee.Effective_Date__c = system.today().addMonths(1);
            fee.Fee_Type__c = 'Annual';
        	insert fee;
        }
        {
        	Fee_History__c fee = new Fee_History__c();
        	fee.Master_Contract__c = con.Id;
        	fee.Amount__c = 100;
        	fee.Effective_Date__c = system.today().addDays(-1);
            fee.Fee_Type__c = 'Hourly';
        	insert fee;
        }
        {
        	Fee_History__c fee = new Fee_History__c();
        	fee.Master_Contract__c = con.Id;
        	fee.Amount__c = 200;
        	fee.Effective_Date__c = system.today().addMonths(1);
            fee.Fee_Type__c = 'Hourly';
        	insert fee;
        }       

        //2. Check that fields are updated to null if required -
        //   no invoices or fee history for second contract
        
        //Initiate Testing Procedure
        Test.startTest();
        
        OptimaFeeHistory.updateHistory();
        
        Test.stopTest();
        
        //Initiate Verification Procedure - test 1
        con = [SELECT Latest_Annual_Fee_History_Date__c, Latest_Hourly_Fee_History_Date__c,
               Latest_Annual_Fee_History_Amount__c, Latest_Hourly_Fee_History_Amount__c, Next_Invoice_Date__c
               FROM IMX_Contract__c WHERE Id = :con.Id];

        //Assert that the correct values were calculated
        System.assertEquals(system.today().addMonths(1),con.Latest_Annual_Fee_History_Date__c);
        System.assertEquals(system.today().addMonths(1),con.Latest_Hourly_Fee_History_Date__c);
        System.assertEquals(200000,con.Latest_Annual_Fee_History_Amount__c);
        System.assertEquals(200,con.Latest_Hourly_Fee_History_Amount__c);
        System.assertEquals(system.today().addDays(1),con.Next_Invoice_Date__c);
        
        //Initiate Verification Procedure - test 2
        con2 = [SELECT Latest_Annual_Fee_History_Date__c, Latest_Hourly_Fee_History_Date__c,
               Latest_Annual_Fee_History_Amount__c, Latest_Hourly_Fee_History_Amount__c, Next_Invoice_Date__c
               FROM IMX_Contract__c WHERE Id = :con2.Id];

        //Assert that the correct values were calculated
        System.assertEquals(null,con2.Latest_Annual_Fee_History_Date__c);
        System.assertEquals(null,con2.Latest_Hourly_Fee_History_Date__c);
        System.assertEquals(null,con2.Latest_Annual_Fee_History_Amount__c);
        System.assertEquals(null,con2.Latest_Hourly_Fee_History_Amount__c);
        System.assertEquals(null,con2.Next_Invoice_Date__c);
        
    }
}