objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Sales_Milestone__c</fullName>
        <label>Sales Milestone</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Interest Generated</fullName>
                    <label>1.1 Interest Generated</label>
                </value>
                <value>
                    <fullName>Information Exchange Mtgs/Calls with additional buyers</fullName>
                    <label>1.2 Information Exchange Mtgs/Calls with additional buyers</label>
                </value>
                <value>
                    <fullName>Initial Understanding: Buyers/Problem/Funding/DRM</fullName>
                    <label>1.3 Initial Understanding: Buyers/Problem/Funding/DRM</label>
                </value>
                <value>
                    <fullName>Test Your Position (A trial walk on the deal)</fullName>
                    <label>1.4 Test Your Position (A trial walk on the deal)</label>
                </value>
                <value>
                    <fullName>RFP/ RFI received</fullName>
                    <label>1.5 RFP/ RFI received</label>
                </value>
                <value>
                    <fullName>1.6 Qualified Opportunity in the Pipeline</fullName>
                </value>
                <value>
                    <fullName>Review Opportunity with Manager (Mini Blue Sheet) and determine pursuit yes or no</fullName>
                    <label>1.7 Review Opportunity with Manager (Mini Blue Sheet) and determine pursuit yes or no</label>
                </value>
                <value>
                    <fullName>An R1 Message is Delivered</fullName>
                    <label>2.1 An R1 Message is Delivered</label>
                </value>
                <value>
                    <fullName>Buyer Identification and Access</fullName>
                    <label>2.2 Buyer Identification and Access</label>
                </value>
                <value>
                    <fullName>Identify and Begin to Develop a Coach(s)</fullName>
                    <label>2.3 Identify and Begin to Develop a Coach(s)</label>
                </value>
                <value>
                    <fullName>Link Clients Timeline to Date Related Motivation (DRM)</fullName>
                    <label>2.4 Link Clients Timeline to Date Related Motivation (DRM)</label>
                </value>
                <value>
                    <fullName>Confirm Funding and Legal Framework</fullName>
                    <label>2.5 Confirm Funding and Legal Framework</label>
                </value>
                <value>
                    <fullName>2.6 Gain agreement for customer to provide data</fullName>
                </value>
                <value>
                    <fullName>2.7 Identify Customer Alternatives to Solve</fullName>
                </value>
                <value>
                    <fullName>2.8 Create Blue Sheet</fullName>
                </value>
                <value>
                    <fullName>First Blue Sheet Session</fullName>
                    <label>2.9 First Blue Sheet Session</label>
                </value>
                <value>
                    <fullName>Deeper Dive(s) with Operations with Client</fullName>
                    <label>3.1 Deeper Dive(s) with Operations with Client</label>
                </value>
                <value>
                    <fullName>Operations and CSE define initial approach statement</fullName>
                    <label>3.2 Operations and CSE define initial approach statement</label>
                </value>
                <value>
                    <fullName>Put our Coach to work (may share approach with coach before you officially share with buyers)</fullName>
                    <label>3.3 Put our Coach to work (may share approach with coach before you officially share with buyers)</label>
                </value>
                <value>
                    <fullName>3.4 Gain Alignment of initial approach with coach(s)</fullName>
                </value>
                <value>
                    <fullName>Test our relative position:  Validate if the client's other alternatives to solve the problem are still viable?</fullName>
                    <label>3.5 Test our relative position:  Validate if the client's other alternatives to solve the problem are still viable?</label>
                </value>
                <value>
                    <fullName>3.6 Deployment Discussion</fullName>
                </value>
                <value>
                    <fullName>3.7 Produce Proposal/SOW/Proforma</fullName>
                </value>
                <value>
                    <fullName>3.8 Proforma Validation with Customer</fullName>
                </value>
                <value>
                    <fullName>3.9 Validate pricing per Internal Approval Guidelines</fullName>
                </value>
                <value>
                    <fullName>4.1 Present initial proposal/SOW/Proforma to Coach</fullName>
                </value>
                <value>
                    <fullName>4.2 Present initial proposal/SOW/Proforma</fullName>
                </value>
                <value>
                    <fullName>4.3 Identify Obstacles to being Vendor of Choice (VOC)</fullName>
                </value>
                <value>
                    <fullName>If necessary, arrange for reference call / site visit</fullName>
                    <label>4.3 If necessary, arrange for reference call / site visit</label>
                </value>
                <value>
                    <fullName>4.4 If necessary, arrange for reference call / site visit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_History__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Enter_DateTime__c</fullName>
        <label>Enter DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Enter_Date__c</fullName>
        <label>Enter Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exit_DateTime__c</fullName>
        <label>Exit DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <label>Exit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MIlestone__c</fullName>
        <label>Milestone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity History</relationshipLabel>
        <relationshipName>Opportunity_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage_History__c</fullName>
        <label>Stage History</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_change__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stage change</label>
        <type>Checkbox</type>
    </fields>
    <label>Opportunity History</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Opportunity History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpportunityHandler.cls
public class OpportunityHandler {
    // Luke Freeland: There's a Salesforce bug where if a workflow rule updates the opportunity again,
    // it causes the trigger to fire again with the same OLD and NEW values so that was causing
    // duplicate Opportunity History records. To fix that, this cache was added to ensure
    // duplicates wouldn't be created.
    private static Map<Id, String> previousOpportunityStages = new Map<Id, String>();
    
    public static void createOpportunityHistory(List<Opportunity> changed)
    {
        // -- Find all opportunities where the stage changed and also pre create the
        // --   new histories to keep it at one loop.
        Set<Id> oppsIds = new Set<Id>();
        List<Opportunity_History__c> newHistories = new List<Opportunity_History__c>();
        for(Opportunity o : changed) {
            String previousStageName = previousOpportunityStages.get(o.Id);
            
            if (String.isBlank(previousStageName) ||
                o.StageName != previousStageName) {
            
                oppsIds.add(o.Id);
                
                Opportunity_History__c history = new Opportunity_History__c();
                history.Enter_Date__c = Date.today();
                history.Enter_DateTime__c = Datetime.now();
                history.Opportunity__c = o.Id;
                history.Amount__c = o.Amount;
                history.Stage_History__c = o.StageName;
                history.Milestone__c = o.Sales_Milestone__c;
                history.Stage_change__c = true;
                                
                newHistories.Add(history);
                previousOpportunityStages.put(o.Id, o.StageName);
            }
        }
        
        if (oppsIds.isEmpty()) {
            return;
        }
        
        // -- Retrieve all the opportunity histories for these that are open (no end date) 
        // --   and close them out.
        List<Opportunity_History__c> histories = [SELECT Id, Exit_Date__c, Exit_DateTime__c, Stage_change__c 
                                                  FROM Opportunity_History__c
                                                  WHERE Exit_DateTime__c = null AND Stage_change__c = TRUE AND Opportunity__c IN :oppsIds];
        
        for(Opportunity_History__c h : histories) {
            h.Exit_Date__c = Date.today();
            h.Exit_DateTime__c = Datetime.now();
        }
        
        update histories;
        
        // -- Create new opportunity histories with the new stage and milestone.        
        insert newHistories; 
    }
}