objects/Optima_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <inlineHelpText>The first day of support covered by the payment (or first day after the support period for invoices in arrears). The invoice is issued in the previous month or earlier, depending on the contract payment terms)</inlineHelpText>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Contract__c</fullName>
        <label>Master Contract</label>
        <referenceTo>IMX_Contract__c</referenceTo>
        <relationshipLabel>Optima Invoices</relationshipLabel>
        <relationshipName>Optima_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Optima Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Optima Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OptimaInvoiceTestData.cls
/**
 * @description Builder class for dealing with Optima_Invoice__c records.
 * Solely used for testing, NOT a data factory.
 **/
@isTest
public with sharing class OptimaInvoiceTestData extends SObjectTestData {
    /**
     * @description Overridden method to set up the default
     * Invoice state for OptimaInvoiceTestData.
     * @return A map of Invoice default fields.
     */
    protected override Map<Schema.SObjectField, Object> getDefaultValueMap() {
        return new Map<Schema.SObjectField, Object>{
        	Optima_Invoice__c.Invoice_Date__c => system.today().addDays(1),
        	Optima_Invoice__c.Amount__c => 100000
        };
    }

    /**
     * @description Returns the SObject type for OptimaInvoiceTestData builder.
     * @return Optima_Invoice__c.SObjectType.
     */
    protected override Schema.SObjectType getSObjectType() {
        return Optima_Invoice__c.SObjectType;
    }

    /* Create a "with" method for each property that can be set */

    /**
     * @description Sets the account on the Invoice.
     * @param accountId The id of the account that the Invoice will have.
     * @return The instance of InvoiceTestData.
     */
    public OptimaInvoiceTestData withContract(Id contractId) {
        return (OptimaInvoiceTestData) withDynamicData(Optima_Invoice__c.Master_Contract__c, contractId);
    }

    /**
     * @description Sets the date of the invoice.
     * @param invoiceDate The date the invoice is due.
     * @return The instance of OptimaInvoiceTestData.
     */
    public OptimaInvoiceTestData withDate(Date invoiceDate) {
        return (OptimaInvoiceTestData) withDynamicData(Optima_Invoice__c.Invoice_Date__c, invoiceDate);
    }

    /**
     * @description Sets the invoice amount.
     * @param amount The amount of the invoice.
     * @return The instance of OptimaInvoiceTestData.
     */
    public OptimaInvoiceTestData withAmount(Integer amount) {
        return (OptimaInvoiceTestData) withDynamicData(Optima_Invoice__c.Amount__c, amount);
    }

    /**
     * @description Sets the invoice number.
     * @param num The number of the invoice.
     * @return The instance of OptimaInvoiceTestData.
     */
    public OptimaInvoiceTestData withNumber(String num) {
        return (OptimaInvoiceTestData) withDynamicData(Optima_Invoice__c.Invoice_Number__c, num);
    }

    /**
     * @description Builds the Invoice object.
     * @return The created Invoice object.
     */
    public Optima_Invoice__c create() {
        return (Optima_Invoice__c)super.buildWithReset();
    }

    /**
     * @description Inserts the built Optima_Invoice__c object.
     * @return The inserted Optima_Invoice__c object.
     */
    public Optima_Invoice__c insertInvoice() {
        return (Optima_Invoice__c)super.insertRecord();
    }

    /**
     * @description Gets an instance of OptimaInvoiceTestData.
     * @return OptimaInvoiceTestData instance.
     */
    private static OptimaInvoiceTestData instancePriv = null;
    public static OptimaInvoiceTestData Instance {
        get {
            if (instancePriv == null) {
                instancePriv = new OptimaInvoiceTestData();
            }
            return instancePriv;
        }
    }

    /**
     * @description Private constructor for singleton.
     */
    private OptimaInvoiceTestData() {
        super();
    }
}